"""Le righe del bestiario della notte, delle stagioni e del tempo (voce 134): le usa tools/gen_bestiario.py.

Campi di condizione: night (solo di notte), season [stagioni di `SeasonsData`], weather [tempi di `WeatherData`],
eclipse (solo durante un'eclissi). Senza «biomes» vivono in tutti i biomi di superficie."""


def P(*cols):
    return list(cols)


def R(out, ins, st, q=1):
    return {'out': out, 'qty': q, 'in': ins, 'station': st}


TIME = [
    dict(id='lupo_lunare', name='Lupo lunare', tier=3, half=[10, 7], speed=115, beh=['cammina', 'carica'], night=True, weight=3,
         p={'sight': 26, 'charge': 250.0, 'charge_range': 8, 'charge_time': 0.6, 'charge_cool': 3.5}, group=[2, 3], glow=True,
         body={'plan': 'quadrupede', 'w': 24, 'h': 18, 'pal': P('#1a1e2e', '#2c3450', '#46547a', '#7a8cb8', '#e0e8ff'), 'eye': '#f0f0a0', 'tail': True, 'marks': 'strisce', 'mark': '#e0e8ff', 'glow': True},
         aff={'weak': ['brace'], 'resist': ['vuoto']}, fam=('lupi_lunari', 'Lupi lunari', False, 'predatore', {'prey': ['lepri', 'pecore']}),
         mat=('pelo_lunare', 'Pelo lunare', ['seta', 'brillaluce'], 'Brilla solo quando c\'è la luna.'),
         trophy=('zanna_lunare', 'Zanna lunare', ['artiglio', 'brillaluce'])),
    dict(id='falena_vampira', name='Falena vampira', tier=2, half=[7, 6], speed=90, fly=True, beh=['vola', 'parassita'], night=True, weight=3,
         p={'sight': 20, 'hover': 10.0, 'wobble': 40.0, 'drain': 2, 'hold': 6.0}, hp=0.7,
         body={'plan': 'insetto', 'w': 18, 'h': 14, 'pal': P('#200a14', '#3a1224', '#5e1e3a', '#9a3a60', '#e080a0'), 'eye': '#ff3050', 'wings': '#5e1e3a', 'marks': 'macchie', 'mark': '#e080a0'},
         aff={'weak': ['luce'], 'resist': ['vuoto']}, fam=('falene_vampire', 'Falene vampire', True, 'volante'),
         mat=('polvere_vampira', 'Polvere di falena vampira', ['polvere', 'sanguinella'], 'Rossa: si attacca alla pelle.'),
         trophy=('ala_vampira', 'Ala vampira', ['membrana', 'sanguinella'])),
    dict(id='bruco_germoglio', name='Bruco del Germoglio', tier=1, half=[8, 4], speed=35, beh=['cammina', 'fugge'], season=['germoglio'], weight=5,
         p={'sight': 10, 'flee': 8}, docile=True, hp=1.2, dmg=0.3, group=[2, 3],
         body={'plan': 'serpe', 'w': 18, 'h': 10, 'pal': P('#1e3014', '#304e20', '#4a7230', '#78a850', '#c8f0a0'), 'eye': '#101010', 'marks': 'macchie', 'mark': '#f0e060'},
         aff={'weak': ['brace'], 'resist': ['spora']}, fam=('bruchi_germoglio', 'Bruchi del Germoglio', False, 'erbivoro', {'nest': {'type': 'erba', 'n': 5}}),
         mat=('seta_germoglio', 'Seta di primavera', ['seta', 'muschio'], 'Il bozzolo non finito di un bruco del Germoglio.'),
         trophy=('bozzolo_germoglio', 'Bozzolo di primavera', ['seme', 'muschio'])),
    dict(id='libellula_rigoglio', name='Libellula del Rigoglio', tier=2, half=[8, 4], speed=130, fly=True, beh=['vola', 'scatto'], season=['rigoglio'], weight=5,
         p={'sight': 24, 'hover': 40.0, 'wobble': 20.0, 'dash_every': 2.5, 'dash_speed': 300.0, 'dash_time': 0.3}, hp=0.7, group=[2, 3],
         body={'plan': 'insetto', 'w': 20, 'h': 10, 'pal': P('#0a2a30', '#10505a', '#1a8090', '#40c0d0', '#c0ffff'), 'eye': '#40ff80', 'wings': '#c0ffff', 'marks': 'strisce', 'mark': '#40ff80'},
         aff={'weak': ['gelo'], 'resist': ['spora']}, fam=('libellule_rigoglio', 'Libellule del Rigoglio', True, 'volante'),
         mat=('ala_libellula', 'Ala di libellula', ['membrana', 'linfa'], 'Leggera come l\'aria d\'estate.'),
         trophy=('occhi_libellula', 'Occhi di libellula', ['gemma', 'linfa'])),
    dict(id='cinghiale_raccolto', name='Cinghiale del Raccolto', tier=2, half=[11, 8], speed=80, beh=['cammina', 'carica'], season=['raccolto'], weight=4,
         p={'sight': 18, 'charge': 230.0, 'charge_range': 8, 'charge_time': 0.7, 'charge_cool': 3.5}, hp=1.4,
         body={'plan': 'quadrupede', 'w': 24, 'h': 18, 'pal': P('#2a1a10', '#4a2e1a', '#70482a', '#a0703e', '#e0b070'), 'eye': '#ff8030', 'horns': 1, 'marks': 'punte', 'mark': '#e0b070'},
         aff={'weak': ['spora'], 'resist': ['gelo']}, fam=('cinghiali', 'Cinghiali del Raccolto', False, 'predatore', {'prey': ['bruchi']}),
         mat=('setola_cinghiale', 'Setola di cinghiale', ['penna', 'ambra'], 'Dura come uno spillo.'),
         trophy=('zanna_cinghiale', 'Zanna di cinghiale', ['artiglio', 'ambra'])),
    dict(id='volpe_gelo', name='Volpe del Gelo', tier=2, half=[9, 6], speed=110, beh=['cammina', 'ladro'], season=['gelo'], weight=4,
         p={'sight': 22, 'steal': 4}, hp=0.9, dmg=0.7,
         body={'plan': 'quadrupede', 'w': 22, 'h': 14, 'pal': P('#8a98a8', '#b0c0d0', '#d8e4f0', '#f4faff', '#ffffff'), 'eye': '#40a0ff', 'tail': True},
         aff={'weak': ['brace'], 'resist': ['gelo']}, fam=('volpi_gelo', 'Volpi del Gelo', True, 'neutro'),
         mat=('coda_gelo', 'Pelo di volpe del Gelo', ['seta', 'brina'], 'Caldo, e profuma di neve.'),
         trophy=('muso_volpe', 'Muso di volpe', ['essenza', 'brina'])),
    dict(id='rana_tuono', name='Rana del tuono', tier=2, half=[7, 6], speed=60, beh=['salta_verso', 'scoppia'], weather=['temporale'], weight=6,
         p={'jump': 240.0, 'sight': 18, 'fuse': 0.9, 'fuse_r': 2.2, 'blast_r': 2.4}, glow=True,
         body={'plan': 'anfibio', 'w': 18, 'h': 14, 'pal': P('#1a1a30', '#2c2c50', '#464680', '#8080d0', '#ffff90'), 'eye': '#ffff60', 'marks': 'punte', 'mark': '#ffff90', 'glow': True},
         aff={'weak': ['spora'], 'resist': ['luce']}, fam=('rane_tuono', 'Rane del tuono', True, 'neutro'),
         mat=('scintilla_rana', 'Scintilla di rana', ['essenza', 'brillaluce'], 'Salta ancora da sola.'),
         trophy=('gola_tuono', 'Gola del tuono', ['gel', 'brillaluce'])),
    dict(id='lumacone_pioggia', name='Lumacone della pioggia', tier=1, half=[9, 5], speed=25, beh=['cammina', 'fugge'], weather=['pioggia', 'temporale'], weight=6,
         p={'sight': 8, 'flee': 6}, docile=True, hp=1.4, dmg=0.3,
         body={'plan': 'lumaca', 'w': 20, 'h': 14, 'pal': P('#1a2430', '#2c3c50', '#465e7a', '#7aa0c0', '#d0f0ff'), 'eye': '#101820', 'marks': 'strisce', 'mark': '#d0f0ff'},
         aff={'weak': ['brace'], 'resist': ['gelo']}, fam=('lumaconi_pioggia', 'Lumaconi della pioggia', False, 'erbivoro'),
         mat=('bava_pioggia', 'Bava di pioggia', ['gel', 'lagunite'], 'Liscia: fa scivolare via l\'acqua.'),
         trophy=('guscio_pioggia', 'Guscio della pioggia', ['scaglia', 'lagunite'])),
    dict(id='velo_nebbia', name='Velo di nebbia', tier=2, half=[8, 8], speed=70, fly=True, beh=['vola', 'fotofobo'], weather=['nebbia'], weight=6,
         p={'sight': 18, 'hover': 20.0, 'wobble': 50.0, 'dark_mult': 1.5},
         body={'plan': 'fluttuante', 'w': 18, 'h': 18, 'pal': P('#3a4048', '#5a626c', '#80888e', '#b0b8bc', '#f0f4f4'), 'eye': '#ff6040', 'marks': 'strisce', 'mark': '#f0f4f4'},
         aff={'weak': ['brace'], 'resist': ['gelo']}, fam=('veli_nebbia', 'Veli di nebbia', False, 'volante'),
         mat=('nebbia_chiusa', 'Nebbia in bottiglia', ['goccia', 'seta'], 'Aprila e non vedi più niente.'),
         trophy=('cuore_nebbia', 'Cuore di nebbia', ['essenza', 'seta'])),
    dict(id='spirito_bufera', name='Spirito della bufera', tier=3, half=[8, 10], speed=100, fly=True, beh=['vola', 'spara'], weather=['bufera'], weight=6,
         p={'sight': 26, 'hover': 70.0, 'wobble': 30.0, 'shot_every': 2.2, 'shot_speed': 220.0, 'shot_look': 'spora'}, glow=True,
         body={'plan': 'fluttuante', 'w': 18, 'h': 22, 'pal': P('#4a6070', '#6a8898', '#98b8c8', '#c8e4f0', '#ffffff'), 'eye': '#40d0ff', 'marks': 'punte', 'mark': '#ffffff', 'glow': True},
         aff={'weak': ['brace'], 'resist': ['gelo']}, fam=('spiriti_bufera', 'Spiriti della bufera', False, 'volante'),
         mat=('neve_eterna', 'Neve eterna', ['polvere', 'brina'], 'Non si scioglie, nemmeno nel fuoco.'),
         trophy=('occhio_bufera', 'Occhio della bufera', ['gemma', 'brina'])),
    dict(id='eclissimo', name='Eclissimo', tier=3, half=[8, 8], speed=90, beh=['cammina', 'mimetico', 'divide'], eclipse=True, weight=8,
         p={'sight': 22, 'look': 'cassa', 'wake': 4.0, 'big_hit': 0.5, 'split_hp': 0.4}, glow=True, dmg=1.2,
         body={'plan': 'fluttuante', 'w': 18, 'h': 18, 'pal': P('#0a0a10', '#1a1420', '#2e2238', '#5a3a6a', '#ffb040'), 'eye': '#ffb040', 'marks': 'punte', 'mark': '#ffb040', 'glow': True},
         aff={'weak': ['luce'], 'resist': ['vuoto']}, fam=('eclissimi', 'Eclissimi', False, 'predatore', {'prey': ['lepri']}),
         mat=('frammento_eclissi', 'Frammento d\'eclissi', ['gemma', 'nottilite'], 'Un pezzo di sole spento.'),
         trophy=('corona_eclissi', 'Corona dell\'eclissi', ['amuleto', 'nottilite'])),
]

TIME_ITEMS = {
    'mantello_lunare': {'name': 'Mantello di pelo lunare', 'kind': 'accessorio', 'icon': ['velo', 'brillaluce'], 'acc': {'halo': 1.3, 'stealth': 0.9}, 'desc': 'Alone +30%; le creature ti notano più tardi.'},
    'unguento_vampiro': {'name': 'Unguento rosso', 'kind': 'consumabile', 'icon': ['pozione', 'sanguinella'], 'boon': ['spine', 180.0], 'stack': 20, 'desc': 'Per 3 minuti chi ti tocca si ferisce.'},
    'fascia_germoglio': {'name': 'Fascia di seta di primavera', 'kind': 'accessorio', 'icon': ['seta', 'muschio'], 'acc': {'regen': 1.1, 'run': 1.03}, 'desc': 'La Vita ricresce +10%; corsa +3%.'},
    'ali_libellula': {'name': 'Ali di libellula', 'kind': 'accessorio', 'icon': ['membrana', 'linfa'], 'acc': {'glide': True, 'run': 1.05}, 'desc': 'Si plana; corsa +5%.'},
    'spazzola_cinghiale': {'name': 'Guanti di setola', 'kind': 'accessorio', 'icon': ['guanto', 'ambra'], 'acc': {'dig': 1.08, 'thorns': 4}, 'desc': 'Scavo +8%; chi ti tocca si punge (4).'},
    'sciarpa_volpe': {'name': 'Sciarpa di volpe del Gelo', 'kind': 'accessorio', 'icon': ['seta', 'brina'], 'acc': {'caldo': 0.6, 'luck': 0.04}, 'desc': 'Freddo: protegge al 60%; fortuna +4%.'},
    'pila_rana': {'name': 'Pila di scintille', 'kind': 'accessorio', 'icon': ['gemma', 'brillaluce'], 'acc': {'magic': 1.08, 'atk_speed': 1.04}, 'desc': 'Incantesimi +8%; colpi +4%.'},
    'cerata_pioggia': {'name': 'Cerata di bava', 'kind': 'accessorio', 'icon': ['velo', 'lagunite'], 'acc': {'acqua': 0.4, 'respiro': 1.3}, 'desc': 'Sete: protegge un poco; respiro +30%.'},
    'bomba_nebbia': {'name': 'Boccia di nebbia', 'kind': 'consumabile', 'icon': ['pozione', 'seta'], 'boon': ['passo', 180.0], 'stack': 20, 'desc': 'Per 3 minuti si corre più svelti nella nebbia che ti porti dietro.'},
    'amuleto_neve': {'name': 'Amuleto di neve eterna', 'kind': 'accessorio', 'icon': ['amuleto', 'brina'], 'acc': {'caldo': 0.5, 'fresco': 0.5}, 'desc': 'Freddo e calore: protegge a metà.'},
    'lente_eclissi': {'name': 'Lente d\'eclissi', 'kind': 'accessorio', 'icon': ['anello', 'nottilite'], 'acc': {'damage': 1.1, 'halo': 0.9}, 'desc': 'Danno +10%, ma un poco meno luce attorno.'},
    'talismano_notte': {'name': 'Talismano della notte', 'kind': 'accessorio', 'icon': ['amuleto', 'brillaluce'], 'acc': {'stealth': 0.8, 'halo': 1.2}, 'desc': 'Le creature ti vedono più tardi; alone +20%.'},
    'talismano_stagioni': {'name': 'Talismano delle quattro stagioni', 'kind': 'accessorio', 'icon': ['amuleto', 'ambra'], 'acc': {'regen': 1.1, 'luck': 0.08, 'caldo': 0.3, 'fresco': 0.3}, 'desc': 'Vita +10%, fortuna +8%; freddo e calore: protegge un poco.'},
    'talismano_tempeste': {'name': 'Talismano delle tempeste', 'kind': 'accessorio', 'icon': ['amuleto', 'lagunite'], 'acc': {'magic': 1.1, 'run': 1.05, 'caldo': 0.3}, 'desc': 'Incantesimi +10%, corsa +5%; freddo: protegge un poco.'},
    'talismano_eclissi': {'name': 'Talismano dell\'eclissi', 'kind': 'accessorio', 'icon': ['amuleto', 'nottilite'], 'acc': {'damage': 1.12, 'stealth': 0.85}, 'desc': 'Danno +12%; le creature ti notano più tardi.'},
}

TIME_RECIPES = [
    R('mantello_lunare', {'pelo_lunare': 10, 'seta_radice': 4}, 'telaio'),
    R('unguento_vampiro', {'polvere_vampira': 2, 'gelatina': 1}, 'alambicco', 2),
    R('fascia_germoglio', {'seta_germoglio': 8, 'seta_radice': 2}, 'telaio'),
    R('ali_libellula', {'ala_libellula': 10, 'seta_radice': 3}, 'telaio'),
    R('spazzola_cinghiale', {'setola_cinghiale': 8, 'seta_radice': 2}, 'telaio'),
    R('sciarpa_volpe', {'coda_gelo': 8, 'seta_radice': 2}, 'telaio'),
    R('pila_rana', {'scintilla_rana': 8, 'lingotto_ambra': 2}, 'maglio'),
    R('cerata_pioggia', {'bava_pioggia': 8, 'seta_radice': 3}, 'telaio'),
    R('bomba_nebbia', {'nebbia_chiusa': 2, 'gelatina': 1}, 'alambicco', 2),
    R('amuleto_neve', {'neve_eterna': 8, 'lingotto_ambra': 2}, 'maglio'),
    R('lente_eclissi', {'frammento_eclissi': 6, 'lingotto_ambra': 2}, 'maglio'),
    R('talismano_notte', {'zanna_lunare': 1, 'ala_vampira': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('talismano_stagioni', {'bozzolo_germoglio': 1, 'occhi_libellula': 1, 'zanna_cinghiale': 1, 'muso_volpe': 1, 'lingotto_ambra': 3}, 'maglio'),
    R('talismano_tempeste', {'gola_tuono': 1, 'guscio_pioggia': 1, 'cuore_nebbia': 1, 'occhio_bufera': 1, 'lingotto_ambra': 3}, 'maglio'),
    R('talismano_eclissi', {'corona_eclissi': 2, 'lingotto_ambra': 2}, 'maglio'),
]
