"""Le creature del cielo (Roadmap 16, voce 160): cinque per bioma del cielo, lette da `gen_bestiario.py`.
Campi in più: `sky` = il bioma del cielo dove nascono, `sw` = il peso nella sua zona (vedi `SkyData.pool_at`).
Il peso normale (`weight`) è 0: non nascono mai fuori dal cielo."""


def P(*cols):
    return list(cols)


def S(**k):
    if 'def_' in k:
        k['def'] = k.pop('def_')
    k.setdefault('weight', 0)
    k.setdefault('strata', [0])
    return dict(**k)


SKY = [
    # ------------------------------------------------------------------ Radici sospese (basso)
    S(id='volpe_planante', name='Volpe planante', tier=2, half=[9, 6], speed=95, beh=['cammina', 'salta_verso'], sky='radici_sospese', sw=5,
      p={'sight': 18, 'jump': 260.0}, knock=0.3,
      body={'plan': 'quadrupede', 'w': 24, 'h': 16, 'pal': P('#2a1a14', '#5a3422', '#8a5634', '#c88a54', '#f0d0a0'), 'eye': '#101010', 'marks': 'strisce', 'mark': '#f0e0c0'},
      aff={'weak': ['gelo'], 'resist': ['linfa']}, fam=('volpi_cielo', 'Volpi plananti', True, 'predatore', {'prey': ['bruchi_cielo', 'lepri_vento']}),
      mat=('membrana_volpe', 'Membrana di volpe planante', ['membrana', 'radice'], 'La pelle tra le zampe: la tiene su nel vento.'),
      trophy=('coda_planante', 'Coda della volpe planante', ['pappo', 'radice'])),
    S(id='bruco_pendente', name='Bruco delle radici pendenti', tier=1, half=[8, 4], speed=35, beh=['cammina'], sky='radici_sospese', sw=6,
      docile=True, hp=1.2,
      body={'plan': 'serpe', 'w': 22, 'h': 10, 'pal': P('#123a3a', '#1f5c58', '#2f8a7c', '#58c0a4', '#a8f0d8'), 'eye': '#f0e060', 'marks': 'macchie', 'mark': '#e8fff6'},
      aff={'weak': ['brace'], 'resist': ['linfa']}, fam=('bruchi_cielo', 'Bruchi del cielo', False, 'erbivoro'),
      mat=('seta_cielo', 'Seta di cielo', ['seta', 'cielo'], 'Il filo con cui i bruchi si calano dalle isole.'),
      trophy=('bozzolo_cielo', 'Bozzolo turchese', ['guscio', 'cielo'])),
    S(id='ape_turchese', name='Ape turchese', tier=2, half=[5, 4], speed=110, fly=True, beh=['vola', 'richiamo'], sky='radici_sospese', sw=5,
      group=[3, 5], hp=0.6, dmg=0.7,
      p={'sight': 20, 'hover': 30.0, 'wobble': 50.0, 'call_time': 1.4, 'call_n': 2, 'calls': 1},
      body={'plan': 'insetto', 'w': 12, 'h': 10, 'pal': P('#0f2a30', '#1f5c58', '#3aa08a', '#8ef0d8', '#fff0a0'), 'eye': '#101010', 'wings': '#d8fff4', 'marks': 'strisce', 'mark': '#fff0a0'},
      aff={'weak': ['gelo'], 'resist': ['spora']}, fam=('api_cielo', 'Api turchesi', True, 'colonia', {'nest': {'type': 'alveare', 'n': 2}}),
      mat=('miele_cielo', 'Miele di cielo', ['goccia', 'cielo'], 'Miele turchese dei fiori sospesi: dolce e freddo.'),
      trophy=('regina_turchese', 'Pungiglione della regina', ['aculeo', 'cielo'])),
    S(id='allocco_radici', name='Allocco delle radici', tier=2, half=[7, 7], speed=100, fly=True, beh=['vola', 'picchiata'], sky='radici_sospese', sw=4,
      night=True, p={'sight': 26, 'hover': 60.0, 'wobble': 20.0, 'rise': 6, 'dive_speed': 300.0, 'dive_every': 5.5},
      body={'plan': 'uccello', 'w': 18, 'h': 18, 'pal': P('#1a1a22', '#3a3440', '#5c5260', '#8e8290', '#d0c8d0'), 'eye': '#ffb030', 'wings': '#3a3440', 'marks': 'macchie', 'mark': '#d0c8d0'},
      aff={'weak': ['luce'], 'resist': ['vuoto']}, fam=('allocchi', 'Allocchi delle radici', False, 'predatore', {'prey': ['bruchi_cielo', 'api_cielo']}),
      mat=('piuma_allocco', "Piuma d'allocco", ['penna', 'radice'], 'Una piuma che non fa rumore.'),
      trophy=('occhio_allocco', "Occhio d'allocco", ['occhio', 'ambra'])),
    S(id='lumacone_sospeso', name='Lumacone sospeso', tier=2, half=[9, 6], speed=30, beh=['cammina', 'guaritore'], sky='radici_sospese', sw=3,
      hp=1.4, p={'heal': 12, 'heal_every': 5.0, 'heal_r': 7},
      body={'plan': 'lumaca', 'w': 22, 'h': 14, 'pal': P('#1a2a28', '#2e4a44', '#4a7466', '#7ab09a', '#c8f0dc'), 'eye': '#f0e060', 'marks': 'macchie', 'mark': '#a8f0d8', 'glow': True},
      aff={'weak': ['brace'], 'resist': ['linfa']}, fam=('lumaconi_cielo', 'Lumaconi sospesi', False, 'neutro'),
      mat=('bava_cielo', 'Bava di lumacone', ['gel', 'cielo'], 'Luccica e cura le ferite delle radici.'),
      trophy=('guscio_sospeso', 'Guscio sospeso', ['guscio', 'muschio'])),
    # ------------------------------------------------------------------ Mare di nuvole (basso)
    S(id='medusa_nuvola', name='Medusa di nuvola', tier=2, half=[8, 9], speed=40, fly=True, beh=['deriva'], sky='mare_nubi', sw=6,
      hp=0.9, knock=0.0, glow=True, p={'drift': 18.0, 'bob': 30.0, 'leash': 16, 'sight': 14},
      body={'plan': 'fluttuante', 'w': 18, 'h': 22, 'pal': P('#6a7a98', '#9aaccc', '#c4d4ec', '#e4eefa', '#ffffff'), 'eye': '#78c0ff', 'glow': True},
      aff={'weak': ['brace'], 'resist': ['gelo']}, fam=('meduse_nubi', 'Meduse di nuvola', True, 'neutro'),
      mat=('velo_nuvola', 'Velo di medusa', ['velo', 'nuvola'], 'Trasparente come la nebbia; punge appena.'),
      trophy=('campana_nuvola', 'Campana di nuvola', ['essenza', 'nuvola'])),
    S(id='pecora_nuvola', name='Pecora di nuvola', tier=1, half=[9, 7], speed=45, beh=['cammina', 'fugge'], sky='mare_nubi', sw=6,
      docile=True, hp=1.3, p={'flee': 10},
      body={'plan': 'quadrupede', 'w': 24, 'h': 18, 'pal': P('#4a5068', '#8a94ac', '#c8d0e4', '#eef2fa', '#ffffff'), 'eye': '#303040', 'horns': 1},
      aff={'weak': ['brace'], 'resist': ['gelo']}, fam=('greggi_nuvola', 'Greggi di nuvola', True, 'erbivoro', {'nest': {'type': 'erba', 'n': 3}}),
      mat=('lana_nuvola', 'Lana di nuvola', ['seta', 'nuvola'], 'Soffice e leggerissima: non trattiene l\'acqua.', 3),
      trophy=('corno_nuvola', 'Corno di montone di nuvola', ['artiglio', 'nuvola'])),
    S(id='nuvolo_vivo', name='Nuvolo vivo', tier=2, half=[9, 7], speed=60, fly=True, beh=['vola', 'divide'], sky='mare_nubi', sw=4,
      p={'sight': 20, 'hover': 20.0, 'wobble': 30.0},
      body={'plan': 'fluttuante', 'w': 22, 'h': 18, 'pal': P('#4a5470', '#7a88a8', '#aebcd8', '#d8e2f4', '#ffffff'), 'eye': '#303040'},
      aff={'weak': ['brace'], 'resist': ['gelo', 'spora']}, fam=('nuvoli', 'Nuvoli vivi', False, 'volante'),
      mat=('vapore_vivo', 'Vapore vivo', ['essenza', 'nuvola'], 'Un fiocco di nuvola che si muove ancora un poco.'),
      trophy=('cuore_nuvolo', 'Cuore del nuvolo', ['cuore', 'nuvola'])),
    S(id='garzetta_nubi', name='Garzetta delle nubi', tier=2, half=[7, 7], speed=110, fly=True, beh=['vola', 'picchiata'], sky='mare_nubi', sw=4,
      p={'sight': 26, 'hover': 50.0, 'wobble': 25.0, 'rise': 6, 'dive_speed': 320.0, 'dive_every': 5.0},
      body={'plan': 'uccello', 'w': 20, 'h': 16, 'pal': P('#3a4250', '#8a94a8', '#d0d8e8', '#f4f8ff', '#ffffff'), 'eye': '#f0c030', 'wings': '#d0d8e8'},
      aff={'weak': ['luce'], 'resist': ['gelo']}, fam=('garzette', 'Garzette delle nubi', True, 'predatore', {'prey': ['greggi_nuvola'], 'nest': {'type': 'erba', 'n': 2}}),
      mat=('piuma_nubi', 'Piuma delle nubi', ['penna', 'nuvola'], 'Bianca e asciutta anche sotto la pioggia.'),
      trophy=('becco_garzetta', 'Becco di garzetta', ['aculeo', 'nuvola'])),
    S(id='spiritello_pioggia', name='Spiritello della pioggia', tier=2, half=[6, 7], speed=80, fly=True, beh=['vola', 'spara'], sky='mare_nubi', sw=3,
      hp=0.8, glow=True, p={'sight': 22, 'hover': 70.0, 'wobble': 40.0, 'rate': 2.4, 'shot_speed': 160.0, 'shot_look': 'goccia'},
      body={'plan': 'fluttuante', 'w': 14, 'h': 18, 'pal': P('#12408a', '#2a7ad8', '#78c0ff', '#d8f0ff', '#ffffff'), 'eye': '#ffffff', 'glow': True},
      aff={'weak': ['gelo'], 'resist': ['brace']}, fam=('spiritelli', 'Spiritelli della pioggia', False, 'volante'),
      mat=('goccia_cielo', 'Goccia di cielo', ['goccia', 'lagunite'], 'Non evapora mai.'),
      trophy=('lacrima_pioggia', 'Lacrima della pioggia', ['gemma', 'lagunite'])),
    # ------------------------------------------------------------------ Giardini del vento (basso)
    S(id='girandola_viva', name='Girandola viva', tier=2, half=[7, 7], speed=50, fly=True, beh=['deriva', 'ventaglio'], sky='giardini_vento', sw=5,
      p={'drift': 30.0, 'bob': 16.0, 'leash': 14, 'sight': 16, 'fan_n': 4, 'fan_rate': 3.4, 'fan_spread': 1.2, 'shot_speed': 140.0},
      body={'plan': 'fluttuante', 'w': 18, 'h': 18, 'pal': P('#6a3a18', '#a06020', '#e0a030', '#ffe070', '#fff8d0'), 'eye': '#101010', 'marks': 'punte', 'mark': '#ff6a78'},
      aff={'weak': ['gelo'], 'resist': ['luce']}, fam=('girandole', 'Girandole vive', True, 'neutro'),
      mat=('pala_girandola', 'Pala di girandola', ['foglia', 'vento'], 'Gira da sola anche quando il vento tace.'),
      trophy=('perno_girandola', 'Perno della girandola', ['gemma', 'vento'])),
    S(id='lepre_vento', name='Lepre del vento', tier=1, half=[7, 6], speed=130, beh=['cammina', 'fugge'], sky='giardini_vento', sw=6,
      docile=True, p={'flee': 14},
      body={'plan': 'quadrupede', 'w': 18, 'h': 16, 'pal': P('#4a3a14', '#7a6020', '#b08c30', '#e0c050', '#fff0c0'), 'eye': '#101010'},
      aff={'weak': ['brace'], 'resist': ['luce']}, fam=('lepri_vento', 'Lepri del vento', True, 'erbivoro', {'nest': {'type': 'tana', 'n': 3}}),
      mat=('pelo_vento', 'Pelo della lepre del vento', ['seta', 'vento'], 'Dorato e leggero; profuma d\'erba secca.'),
      trophy=('zampa_vento', 'Zampa portafortuna', ['artiglio', 'vento'])),
    S(id='falco_vento', name='Falco del vento', tier=3, half=[8, 7], speed=130, fly=True, beh=['vola', 'picchiata'], sky='giardini_vento', sw=4,
      p={'sight': 30, 'hover': 70.0, 'wobble': 20.0, 'rise': 8, 'dive_speed': 360.0, 'dive_every': 4.5},
      body={'plan': 'uccello', 'w': 22, 'h': 16, 'pal': P('#2a1a0a', '#5a3a14', '#8a6020', '#c09040', '#f0e0b0'), 'eye': '#ffd24a', 'wings': '#5a3a14', 'marks': 'strisce', 'mark': '#f0e0b0'},
      aff={'weak': ['gelo'], 'resist': ['luce']}, fam=('falchi_vento', 'Falchi del vento', False, 'predatore', {'prey': ['lepri_vento', 'cavallette_oro']}),
      mat=('penna_falco_vento', 'Penna del falco del vento', ['penna', 'vento'], 'Lunga e rigida: taglia l\'aria.'),
      trophy=('artiglio_falco_vento', 'Artiglio del falco', ['artiglio', 'vento'])),
    S(id='cavalletta_oro', name='Cavalletta dorata', tier=2, half=[6, 4], speed=90, beh=['salta_verso'], sky='giardini_vento', sw=5,
      group=[3, 6], hp=0.6, dmg=0.6, p={'sight': 14, 'jump': 280.0},
      body={'plan': 'insetto', 'w': 14, 'h': 10, 'pal': P('#3a3010', '#6a5418', '#b08c30', '#e0c050', '#fff0a0'), 'eye': '#101010', 'wings': '#fff0a0'},
      aff={'weak': ['brace'], 'resist': ['luce']}, fam=('cavallette_oro', 'Cavallette dorate', True, 'colonia'),
      mat=('zampa_cavalletta', 'Zampa di cavalletta', ['aculeo', 'vento'], 'Una molla perfetta.'),
      trophy=('ala_oro', "Ala d'oro", ['foglia', 'ambra'])),
    S(id='gazza_vento', name='Gazza ladra del vento', tier=2, half=[7, 6], speed=120, fly=True, beh=['vola', 'ladro'], sky='giardini_vento', sw=3,
      hp=0.8, p={'sight': 24, 'hover': 30.0, 'wobble': 30.0, 'steal': 3, 'steal_cool': 12.0},
      body={'plan': 'uccello', 'w': 18, 'h': 14, 'pal': P('#101418', '#2a3038', '#4a5260', '#d0d8e0', '#ffffff'), 'eye': '#ffd24a', 'wings': '#2a3038', 'marks': 'strisce', 'mark': '#ffffff'},
      aff={'weak': ['luce'], 'resist': ['gelo']}, fam=('gazze', 'Gazze del vento', True, 'volante'),
      mat=('piuma_gazza', 'Piuma di gazza', ['penna', 'nottilite'], 'Nera e bianca, con un riflesso blu.'),
      trophy=('nido_gazza', 'Nido pieno di gazza', ['cesta', 'vento'])),
    # ------------------------------------------------------------------ Scogliere di cristallo (alto)
    S(id='geco_cristallo', name='Geco di cristallo', tier=3, half=[8, 4], speed=80, beh=['cammina', 'mimetico'], sky='scogliere_cristallo', sw=5,
      glow=True, p={'look': 'cristallo_celeste', 'wake': 3},
      body={'plan': 'anfibio', 'w': 20, 'h': 10, 'pal': P('#1a3a5a', '#2a6090', '#4a90c8', '#8ac8f0', '#e0f6ff'), 'eye': '#ffffff', 'marks': 'punte', 'mark': '#e0f6ff', 'glow': True},
      aff={'weak': ['brace'], 'resist': ['gelo', 'luce']}, fam=('gechi_cristallo', 'Gechi di cristallo', False, 'predatore', {'prey': ['farfalle_prisma']}),
      mat=('scaglia_celeste', 'Scaglia celeste', ['scaglia', 'celeste'], 'Una scaglia che si scambia per un cristallo.'),
      trophy=('coda_cristallo', 'Coda di cristallo', ['cristallo', 'celeste'])),
    S(id='farfalla_prisma', name='Farfalla prisma', tier=3, half=[6, 6], speed=90, fly=True, beh=['vola', 'teletrasporto'], sky='scogliere_cristallo', sw=5,
      hp=0.6, dmg=0.6, glow=True, p={'sight': 20, 'hover': 40.0, 'wobble': 50.0, 'blink_every': 4.0},
      body={'plan': 'insetto', 'w': 16, 'h': 14, 'pal': P('#2a3a6a', '#3aa0c8', '#8ac8f0', '#f0c050', '#fff0f8'), 'eye': '#ffffff', 'wings': '#8ac8f0', 'glow': True},
      aff={'weak': ['vuoto'], 'resist': ['luce']}, fam=('farfalle_prisma', 'Farfalle prisma', True, 'volante'),
      mat=('polvere_prisma', 'Polvere di prisma', ['polvere', 'celeste'], 'Scompone la luce in sette colori.'),
      trophy=('ala_prisma', 'Ala di prisma', ['foglia', 'iride'])),
    S(id='sentinella_cristallo', name='Sentinella di cristallo', tier=3, half=[8, 10], speed=40, beh=['cammina', 'scudo', 'spara'], sky='scogliere_cristallo', sw=3,
      hp=1.6, def_=0, p={'sight': 22, 'turn': 1.4, 'rate': 3.0, 'shot_speed': 180.0, 'shot_look': 'cristallo'},
      body={'plan': 'quadrupede', 'w': 20, 'h': 22, 'pal': P('#1a2a4a', '#2a4a7a', '#4a7ab0', '#8ab0e0', '#e0f0ff'), 'eye': '#fff0a0', 'marks': 'punte', 'mark': '#e0f0ff'},
      aff={'weak': ['vuoto'], 'resist': ['gelo', 'luce']}, fam=('sentinelle_cielo', 'Sentinelle di cristallo', False, 'neutro'),
      mat=('nucleo_celeste', 'Nucleo celeste', ['gemma', 'celeste'], 'Il cuore di una sentinella: pulsa piano.'),
      trophy=('scudo_cristallo', 'Scudo di cristallo', ['scudo', 'celeste'])),
    S(id='draghetto_eco', name="Draghetto dell'eco", tier=3, half=[9, 6], speed=100, fly=True, beh=['vola', 'ventaglio'], sky='scogliere_cristallo', sw=3,
      p={'sight': 24, 'hover': 50.0, 'wobble': 30.0, 'fan_n': 3, 'fan_rate': 3.0, 'fan_spread': 0.5, 'shot_speed': 170.0},
      body={'plan': 'serpe', 'w': 24, 'h': 12, 'pal': P('#14304a', '#1f5078', '#3a80b0', '#8ac8f0', '#e0f6ff'), 'eye': '#ffd24a', 'wings': '#8ac8f0', 'marks': 'punte', 'mark': '#e0f6ff'},
      aff={'weak': ['brace'], 'resist': ['gelo']}, fam=('draghetti', "Draghetti dell'eco", False, 'predatore', {'prey': ['farfalle_prisma']}),
      mat=('squama_eco', "Squama dell'eco", ['scaglia', 'celeste'], 'Se la batti, risponde con la stessa nota.'),
      trophy=('gola_eco', "Gola dell'eco", ['essenza', 'celeste'])),
    S(id='riccio_cristallo', name='Riccio di cristallo', tier=3, half=[7, 6], speed=45, beh=['cammina', 'guscio'], sky='scogliere_cristallo', sw=4,
      hp=1.2, def_=2,
      body={'plan': 'quadrupede', 'w': 18, 'h': 14, 'pal': P('#2a3a50', '#4a6a8a', '#8ab0d0', '#c8e4f8', '#ffffff'), 'eye': '#101010', 'marks': 'punte', 'mark': '#ffffff'},
      aff={'weak': ['brace'], 'resist': ['gelo', 'luce']}, fam=('ricci_cristallo', 'Ricci di cristallo', False, 'erbivoro'),
      mat=('aculeo_celeste', 'Aculeo celeste', ['aculeo', 'celeste'], 'Trasparente e durissimo.'),
      trophy=('corona_aculei', 'Corona di aculei', ['corona', 'celeste'])),
    # ------------------------------------------------------------------ Nidi di tempesta (alto)
    S(id='nube_tuono', name='Nube del tuono', tier=3, half=[10, 8], speed=50, fly=True, beh=['vola', 'folgore'], sky='nidi_tempesta', sw=5,
      glow=True, p={'sight': 24, 'hover': 90.0, 'wobble': 20.0, 'bolt_every': 5.0, 'bolt_delay': 1.0},
      body={'plan': 'fluttuante', 'w': 24, 'h': 18, 'pal': P('#1a1e2e', '#2c3248', '#434c68', '#66729a', '#fffac0'), 'eye': '#fffac0', 'glow': True},
      aff={'weak': ['spora'], 'resist': ['luce', 'gelo']}, fam=('nubi_tuono', 'Nubi del tuono', True, 'volante'),
      mat=('scintilla_tuono', 'Scintilla di tuono', ['stella', 'folgorite'], 'Salta da una mano all\'altra, ma non brucia.'),
      trophy=('occhio_tuono', 'Occhio del tuono', ['occhio', 'folgorite'])),
    S(id='aquila_tempesta', name='Aquila della tempesta', tier=4, half=[10, 8], speed=130, fly=True, beh=['vola', 'picchiata'], sky='nidi_tempesta', sw=4,
      p={'sight': 32, 'hover': 80.0, 'wobble': 20.0, 'rise': 9, 'dive_speed': 380.0, 'dive_every': 4.5},
      body={'plan': 'uccello', 'w': 26, 'h': 18, 'pal': P('#14182a', '#2a3048', '#4a5478', '#8a98c8', '#fffac0'), 'eye': '#fffac0', 'wings': '#2a3048', 'marks': 'punte', 'mark': '#fffac0'},
      aff={'weak': ['spora'], 'resist': ['luce']}, fam=('aquile_tempesta', 'Aquile della tempesta', True, 'predatore', {'prey': ['anguille_vento']}),
      mat=('penna_tempesta', 'Penna della tempesta', ['penna', 'tempesta'], 'Crepita quando la pieghi.'),
      trophy=('artiglio_tempesta', 'Artiglio della tempesta', ['artiglio', 'folgorite'])),
    S(id='anguilla_vento', name='Anguilla del vento', tier=3, half=[11, 4], speed=120, fly=True, beh=['vola', 'scatto'], sky='nidi_tempesta', sw=4,
      p={'sight': 26, 'hover': 30.0, 'wobble': 60.0, 'dash_every': 3.5, 'dash_speed': 330.0, 'dash_time': 0.45},
      body={'plan': 'serpe', 'w': 28, 'h': 10, 'pal': P('#101828', '#243450', '#3a5480', '#7a98c8', '#c0d0ff'), 'eye': '#fffac0', 'marks': 'strisce', 'mark': '#c0d0ff'},
      aff={'weak': ['spora'], 'resist': ['luce', 'gelo']}, fam=('anguille_vento', 'Anguille del vento', False, 'neutro'),
      mat=('pelle_anguilla', "Pelle d'anguilla del vento", ['membrana', 'tempesta'], 'Liscia, fredda, carica.'),
      trophy=('coda_anguilla', "Coda d'anguilla", ['frusta', 'tempesta'])),
    S(id='scintilla_viva', name='Scintilla viva', tier=3, half=[5, 5], speed=100, fly=True, beh=['vola', 'scoppia'], sky='nidi_tempesta', sw=3,
      group=[2, 4], hp=0.5, glow=True, p={'sight': 18, 'hover': 10.0, 'wobble': 60.0, 'fuse': 0.8, 'fuse_r': 1.6, 'blast_r': 2.0},
      body={'plan': 'fluttuante', 'w': 12, 'h': 12, 'pal': P('#2a2450', '#4a4a9a', '#7a8ae0', '#c0d0ff', '#fffac0'), 'eye': '#ffffff', 'glow': True},
      aff={'weak': ['gelo'], 'resist': ['luce']}, fam=('scintille', 'Scintille vive', False, 'volante'),
      mat=('polvere_scintilla', 'Polvere di scintilla', ['polvere', 'folgorite'], 'Crepita nel pugno.'),
      trophy=('nucleo_scintilla', 'Nucleo di scintilla', ['stella', 'folgorite'])),
    S(id='corvo_nembo', name='Corvo del nembo', tier=3, half=[8, 7], speed=110, fly=True, beh=['vola', 'richiamo', 'folgore'], sky='nidi_tempesta', sw=3,
      p={'sight': 26, 'hover': 50.0, 'wobble': 30.0, 'call_time': 1.6, 'call_n': 2, 'calls': 1, 'call_id': 'scintilla_viva', 'bolt_every': 7.0, 'bolt_delay': 1.1},
      body={'plan': 'uccello', 'w': 20, 'h': 16, 'pal': P('#08080e', '#1a1a28', '#2e2e48', '#5a5a88', '#c0c0ff'), 'eye': '#fffac0', 'wings': '#1a1a28'},
      aff={'weak': ['luce'], 'resist': ['vuoto']}, fam=('corvi_nembo', 'Corvi del nembo', False, 'predatore', {'prey': ['scintille']}),
      mat=('piuma_nembo', 'Piuma del nembo', ['penna', 'tempesta'], 'Nera come la nuvola prima del tuono.'),
      trophy=('becco_nembo', 'Becco del nembo', ['aculeo', 'tempesta'])),
    # ------------------------------------------------------------------ Il Firmamento (alto)
    S(id='balena_stelle', name='Balena delle stelle', tier=4, half=[20, 10], speed=35, fly=True, beh=['deriva'], sky='firmamento', sw=3,
      docile=True, hp=3.0, knock=0.0, glow=True, p={'drift': 14.0, 'bob': 20.0, 'leash': 26, 'sight': 18},
      body={'plan': 'fluttuante', 'w': 44, 'h': 22, 'pal': P('#101430', '#1c2450', '#2e3a78', '#6a78c0', '#f0f0ff'), 'eye': '#fff0a0', 'marks': 'macchie', 'mark': '#fffbe0', 'glow': True},
      aff={'weak': ['vuoto'], 'resist': ['luce', 'gelo']}, fam=('balene_stelle', 'Balene delle stelle', True, 'erbivoro'),
      mat=('ambra_stelle', 'Ambra di stelle', ['gemma', 'stelle'], 'Una goccia d\'ambra con dentro una costellazione.'),
      trophy=('canto_balena', 'Canto della balena', ['essenza', 'stelle'])),
    S(id='stella_errante', name='Stella errante', tier=4, half=[7, 7], speed=90, fly=True, beh=['vola', 'teletrasporto', 'spara'], sky='firmamento', sw=4,
      glow=True, p={'sight': 26, 'hover': 60.0, 'wobble': 30.0, 'blink_every': 5.0, 'rate': 2.2, 'shot_speed': 200.0, 'shot_look': 'stella'},
      body={'plan': 'fluttuante', 'w': 16, 'h': 16, 'pal': P('#4a3a10', '#a08020', '#f0c050', '#fff0a0', '#ffffff'), 'eye': '#ffffff', 'marks': 'punte', 'mark': '#ffffff', 'glow': True},
      aff={'weak': ['vuoto'], 'resist': ['luce']}, fam=('stelle_erranti', 'Stelle erranti', True, 'volante'),
      mat=('scheggia_stella', 'Scheggia di stella', ['stella', 'stelle'], 'Calda, anche dopo cent\'anni.'),
      trophy=('cuore_stella', 'Cuore di stella', ['cuore', 'ambra'])),
    S(id='falena_firmamento', name='Falena del firmamento', tier=3, half=[7, 6], speed=85, fly=True, beh=['vola', 'fotofobo'], sky='firmamento', sw=5,
      hp=0.8, p={'sight': 22, 'hover': 30.0, 'wobble': 60.0, 'dark_mult': 1.6},
      body={'plan': 'insetto', 'w': 18, 'h': 14, 'pal': P('#101430', '#2a3060', '#4a58a0', '#8a98e0', '#e0e8ff'), 'eye': '#fff0a0', 'wings': '#4a58a0', 'marks': 'macchie', 'mark': '#fff0a0'},
      aff={'weak': ['luce'], 'resist': ['vuoto']}, fam=('falene_firmamento', 'Falene del firmamento', True, 'volante'),
      mat=('polvere_falena', 'Polvere di falena stellata', ['polvere', 'stelle'], 'Fa brillare ciò che tocca, per un poco.'),
      trophy=('antenna_falena', 'Antenna della falena', ['pappo', 'stelle'])),
    S(id='custode_orbita', name="Custode d'orbita", tier=4, half=[9, 9], speed=60, fly=True, beh=['vola', 'bombarda'], sky='firmamento', sw=3,
      hp=1.4, p={'sight': 26, 'hover': 110.0, 'wobble': 10.0, 'rate': 2.6, 'shot_look': 'stella'},
      body={'plan': 'fluttuante', 'w': 20, 'h': 20, 'pal': P('#1a1a3a', '#2e2e60', '#4a4a90', '#8080c8', '#e0e0ff'), 'eye': '#fff0a0', 'marks': 'punte', 'mark': '#e0e0ff', 'glow': True},
      aff={'weak': ['spora'], 'resist': ['vuoto', 'luce']}, fam=('custodi_orbita', "Custodi d'orbita", False, 'neutro'),
      mat=('anello_orbita', "Anello d'orbita", ['anello', 'stelle'], 'Gira attorno al dito da solo.'),
      trophy=('occhio_orbita', "Occhio d'orbita", ['occhio', 'stelle'])),
    S(id='mangiastelle', name='Mangiastelle', tier=4, half=[9, 6], speed=70, beh=['cammina', 'sbuca'], sky='firmamento', sw=3,
      hp=1.3, p={'sight': 18, 'out_time': 2.4, 'windup': 1.0},
      body={'plan': 'serpe', 'w': 26, 'h': 14, 'pal': P('#0c0e22', '#1c2040', '#34386a', '#5a60a0', '#fffbe0'), 'eye': '#fff0a0', 'marks': 'macchie', 'mark': '#fffbe0'},
      aff={'weak': ['luce'], 'resist': ['vuoto']}, fam=('rosicchiastelle', 'Mangiastelle', False, 'scavatore'),
      mat=('dente_stelle', 'Dente del mangiastelle', ['aculeo', 'stelle'], 'Ha rosicchiato stelle cadute per secoli.'),
      trophy=('ventre_stelle', 'Ventre di stelle', ['sacca', 'stelle'])),
]

R = lambda out, ins, st, q=1: {'out': out, 'qty': q, 'in': ins, 'station': st}

SKY_ITEMS = {
    # un talismano per bioma del cielo (dai trofei), e qualche oggetto dei materiali delle creature
    'talismano_radici_cielo': {'name': 'Talismano delle radici sospese', 'kind': 'accessorio', 'icon': ['amuleto', 'cielo'], 'stack': 1,
                               'acc': {'glide': True, 'regen': 1.1}, 'desc': 'Si plana tenendo il salto; la Vita ricresce +10%.'},
    'talismano_nubi': {'name': 'Talismano del mare di nuvole', 'kind': 'accessorio', 'icon': ['amuleto', 'nuvola'], 'stack': 1,
                       'acc': {'fall_safe': True, 'defense': 2}, 'desc': 'Le cadute non fanno male; +2 Scorza.'},
    'talismano_vento_cielo': {'name': 'Talismano dei giardini del vento', 'kind': 'accessorio', 'icon': ['amuleto', 'vento'], 'stack': 1,
                              'acc': {'run': 1.08, 'jump': 1.08}, 'desc': 'Corsa +8%, salto +8%.'},
    'talismano_cristallo_cielo': {'name': 'Talismano delle scogliere', 'kind': 'accessorio', 'icon': ['amuleto', 'celeste'], 'stack': 1,
                                  'acc': {'quota': 0.4, 'halo': 1.3}, 'desc': "Aria sottile: protegge al 40%; alone più ampio."},
    'talismano_tempesta': {'name': 'Talismano della tempesta', 'kind': 'accessorio', 'icon': ['amuleto', 'folgorite'], 'stack': 1,
                           'acc': {'damage': 1.08, 'atk_speed': 1.06}, 'desc': 'Danno +8%, colpi +6% più rapidi.'},
    'talismano_firmamento': {'name': 'Talismano del Firmamento', 'kind': 'accessorio', 'icon': ['amuleto', 'stelle'], 'stack': 1,
                             'acc': {'quota': 0.5, 'luck': 0.08}, 'desc': "Aria sottile: protegge a metà; fortuna +8%."},
    'mantello_nembo': {'name': 'Mantello del nembo', 'kind': 'accessorio', 'icon': ['mantello', 'tempesta'], 'stack': 1,
                       'acc': {'glide': True, 'air_jumps': 1}, 'desc': 'Un salto in più in aria; si plana tenendo il salto.'},
    'occhiali_prisma': {'name': 'Occhiali di prisma', 'kind': 'accessorio', 'icon': ['specchio', 'celeste'], 'stack': 1,
                        'acc': {'quota': 0.3, 'halo': 1.2, 'luck': 0.03}, 'desc': "Aria sottile: protegge al 30%; alone più ampio; un po' di fortuna."},
    'dardo_prisma': {'name': 'Dardo di prisma', 'kind': 'munizione', 'icon': ['freccia', 'celeste'], 'damage': 9, 'stack': 999,
                     'desc': 'Punta di scaglia celeste: vola dritto e acceca.'},
    'miele_cielo_vasetto': {'name': 'Vasetto di miele di cielo', 'kind': 'consumabile', 'icon': ['vasetto', 'cielo'], 'stack': 20,
                            'boon': ['respiro_alto', 120.0], 'desc': "Per 2 minuti l'aria sottile non ti tocca."},
}

SKY_RECIPES = [
    R('talismano_radici_cielo', {'coda_planante': 1, 'bozzolo_cielo': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('talismano_nubi', {'campana_nuvola': 1, 'corno_nuvola': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('talismano_vento_cielo', {'zampa_vento': 1, 'artiglio_falco_vento': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('talismano_cristallo_cielo', {'coda_cristallo': 1, 'ala_prisma': 1, 'lingotto_nimbite': 2}, 'maglio'),
    R('talismano_tempesta', {'occhio_tuono': 1, 'artiglio_tempesta': 1, 'lingotto_nimbite': 2}, 'maglio'),
    R('talismano_firmamento', {'cuore_stella': 1, 'canto_balena': 1, 'lingotto_nimbite': 3}, 'maglio'),
    R('mantello_nembo', {'penna_tempesta': 8, 'piuma_nembo': 6, 'seta_cielo': 4}, 'telaio'),
    R('occhiali_prisma', {'polvere_prisma': 6, 'cristallo_celeste': 2, 'lingotto_nimbite': 1}, 'mola'),
    R('dardo_prisma', {'scaglia_celeste': 1, 'legno': 2}, 'ceppo', 25),
    R('miele_cielo_vasetto', {'miele_cielo': 3}, 'alambicco', 2),
]

SKY_ITEMS.update({
    # gli emblemi: gli altri tre trofei di ogni bioma
    'emblema_radici_cielo': {'name': 'Emblema delle radici sospese', 'kind': 'accessorio', 'icon': ['collana', 'cielo'], 'stack': 1,
                             'acc': {'regen': 1.15, 'halo': 1.2}, 'desc': 'La Vita ricresce +15%; alone più ampio.'},
    'emblema_nubi': {'name': 'Emblema del mare di nuvole', 'kind': 'accessorio', 'icon': ['collana', 'nuvola'], 'stack': 1,
                     'acc': {'respiro': 1.5, 'defense': 2}, 'desc': "Respiro sott'acqua +50%; +2 Scorza."},
    'emblema_vento': {'name': 'Emblema dei giardini del vento', 'kind': 'accessorio', 'icon': ['collana', 'vento'], 'stack': 1,
                      'acc': {'luck': 0.06, 'run': 1.05}, 'desc': 'Fortuna +6%; corsa +5%.'},
    'emblema_cristallo': {'name': 'Emblema delle scogliere', 'kind': 'accessorio', 'icon': ['collana', 'celeste'], 'stack': 1,
                          'acc': {'defense': 4, 'thorns': 8}, 'desc': '+4 Scorza; chi ti tocca si ferisce (8).'},
    'emblema_tempesta': {'name': 'Emblema della tempesta', 'kind': 'accessorio', 'icon': ['collana', 'folgorite'], 'stack': 1,
                         'acc': {'atk_speed': 1.08, 'damage': 1.05}, 'desc': 'Colpi +8% più rapidi; danno +5%.'},
    'emblema_firmamento': {'name': 'Emblema del Firmamento', 'kind': 'accessorio', 'icon': ['collana', 'stelle'], 'stack': 1,
                           'acc': {'magic': 1.12, 'linfa_regen': 1.2}, 'desc': 'Incantesimi +12%; Linfa +20%.'},
    # dai materiali delle creature
    'mantello_volpe': {'name': 'Mantello di membrana', 'kind': 'accessorio', 'icon': ['mantello', 'radice'], 'stack': 1,
                       'acc': {'glide': True, 'run': 1.05}, 'desc': 'Si plana tenendo il salto; corsa +5%.'},
    'cappuccio_allocco': {'name': "Cappuccio d'allocco", 'kind': 'accessorio', 'icon': ['velo', 'radice'], 'stack': 1,
                          'acc': {'stealth': 0.8}, 'desc': 'Le creature ti notano più tardi.'},
    'mantello_lana_nuvola': {'name': 'Mantello di lana di nuvola', 'kind': 'accessorio', 'icon': ['mantello', 'nuvola'], 'stack': 1,
                             'acc': {'caldo': 0.6, 'quota': 0.3}, 'desc': 'Freddo: protegge al 60%; aria sottile al 30%.'},
    'dardo_nubi': {'name': 'Dardo delle nubi', 'kind': 'munizione', 'icon': ['freccia', 'nuvola'], 'damage': 7, 'stack': 999,
                   'desc': 'Impennato di piume delle nubi: leggero e preciso.'},
    'girandola_tasca': {'name': 'Girandola da tasca', 'kind': 'accessorio', 'icon': ['stella', 'vento'], 'stack': 1,
                        'acc': {'vento': 1.4, 'glide': True}, 'desc': 'Il vento ti porta più lontano quando plani.'},
    'stivali_vento_cielo': {'name': 'Stivali di pelo di lepre', 'kind': 'accessorio', 'icon': ['stivali', 'vento'], 'stack': 1,
                            'acc': {'run': 1.1}, 'desc': 'Corsa +10%.'},
    'dardo_falco': {'name': 'Dardo di falco', 'kind': 'munizione', 'icon': ['freccia', 'vento'], 'damage': 8, 'stack': 999,
                    'desc': "Penna di falco del vento: taglia l'aria."},
    'molle_cavalletta': {'name': 'Molle di cavalletta', 'kind': 'accessorio', 'icon': ['stivali', 'ambra'], 'stack': 1,
                         'acc': {'jump': 1.12}, 'desc': 'Salto +12%.'},
    'amuleto_gazza': {'name': 'Amuleto della gazza', 'kind': 'accessorio', 'icon': ['amuleto', 'nottilite'], 'stack': 1,
                      'acc': {'luck': 0.05}, 'desc': 'Fortuna +5%: le cose luccicanti ti trovano.'},
    'lanterna_celeste': {'name': 'Lanterna celeste', 'kind': 'accessorio', 'icon': ['lanterna', 'celeste'], 'stack': 1,
                         'acc': {'halo': 1.4}, 'desc': 'Alone di luce più ampio.'},
    'elmetto_eco': {'name': "Elmetto dell'eco", 'kind': 'accessorio', 'icon': ['elmo', 'celeste'], 'stack': 1,
                    'acc': {'defense': 3, 'stealth': 0.9}, 'desc': '+3 Scorza; le creature ti notano un poco più tardi.'},
    'guanti_anguilla': {'name': "Guanti di pelle d'anguilla", 'kind': 'accessorio', 'icon': ['guanti', 'tempesta'], 'stack': 1,
                        'acc': {'atk_speed': 1.08}, 'desc': 'Colpi +8% più rapidi.'},
    'anello_stelle': {'name': 'Anello di ambra di stelle', 'kind': 'accessorio', 'icon': ['anello', 'stelle'], 'stack': 1,
                      'acc': {'luck': 0.06, 'magic': 1.06}, 'desc': 'Fortuna +6%; incantesimi +6%.'},
    'dardo_stella': {'name': 'Dardo di stella', 'kind': 'munizione', 'icon': ['freccia', 'stelle'], 'damage': 12, 'stack': 999,
                     'desc': 'Una scheggia di stella in punta: il dardo più forte del cielo.'},
    'polvere_luminosa': {'name': 'Polvere luminosa', 'kind': 'consumabile', 'icon': ['polvere', 'stelle'], 'stack': 20,
                         'boon': ['bagliore', 180.0], 'desc': 'Per 3 minuti brilli come una falena.'},
    'anello_orbita_forgiato': {'name': "Anello d'orbita forgiato", 'kind': 'accessorio', 'icon': ['anello', 'nimbite'], 'stack': 1,
                               'acc': {'magic': 1.1}, 'desc': 'Incantesimi +10%.'},
    'collana_denti_stelle': {'name': 'Collana di denti di stelle', 'kind': 'accessorio', 'icon': ['collana', 'stelle'], 'stack': 1,
                             'acc': {'damage': 1.06, 'luck': 0.03}, 'desc': "Danno +6%; un po' di fortuna."},
})

SKY_RECIPES += [
    R('emblema_radici_cielo', {'regina_turchese': 1, 'occhio_allocco': 1, 'guscio_sospeso': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('emblema_nubi', {'cuore_nuvolo': 1, 'becco_garzetta': 1, 'lacrima_pioggia': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('emblema_vento', {'perno_girandola': 1, 'ala_oro': 1, 'nido_gazza': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('emblema_cristallo', {'scudo_cristallo': 1, 'gola_eco': 1, 'corona_aculei': 1, 'lingotto_nimbite': 2}, 'maglio'),
    R('emblema_tempesta', {'coda_anguilla': 1, 'nucleo_scintilla': 1, 'becco_nembo': 1, 'lingotto_nimbite': 2}, 'maglio'),
    R('emblema_firmamento', {'antenna_falena': 1, 'occhio_orbita': 1, 'ventre_stelle': 1, 'lingotto_nimbite': 3}, 'maglio'),
    R('mantello_volpe', {'membrana_volpe': 8, 'seta_cielo': 2}, 'telaio'),
    R('cappuccio_allocco', {'piuma_allocco': 8, 'seta_cielo': 2}, 'telaio'),
    R('fagiolo_nuvola', {'bava_cielo': 2, 'legno': 4}, 'ceppo', 3),
    R('elisir_respiro', {'velo_nuvola': 2, 'goccia_cielo': 1}, 'alambicco', 2),
    R('mantello_lana_nuvola', {'lana_nuvola': 12, 'seta_cielo': 3}, 'telaio'),
    R('nuvola', {'vapore_vivo': 1}, 'ceppo', 12),
    R('dardo_nubi', {'piuma_nubi': 1, 'legno': 2}, 'ceppo', 25),
    R('girandola_tasca', {'pala_girandola': 6, 'lingotto_ambra': 1}, 'maglio'),
    R('stivali_vento_cielo', {'pelo_vento': 10, 'seta_cielo': 2}, 'telaio'),
    R('dardo_falco', {'penna_falco_vento': 1, 'legno': 2}, 'ceppo', 25),
    R('molle_cavalletta', {'zampa_cavalletta': 10, 'seta_cielo': 2}, 'telaio'),
    R('amuleto_gazza', {'piuma_gazza': 8, 'lingotto_ambra': 1}, 'maglio'),
    R('lanterna_celeste', {'nucleo_celeste': 2, 'cristallo_celeste': 4, 'lingotto_nimbite': 1}, 'maglio'),
    R('elmetto_eco', {'squama_eco': 10, 'lingotto_nimbite': 2}, 'maglio'),
    R('dardo_prisma', {'aculeo_celeste': 1, 'legno': 2}, 'ceppo', 25),
    R('baccello_tuono', {'scintilla_tuono': 2, 'gelatina': 2}, 'maglio', 3),
    R('guanti_anguilla', {'pelle_anguilla': 8, 'seta_cielo': 2}, 'telaio'),
    R('dardo_folgore', {'polvere_scintilla': 1, 'legno': 2}, 'ceppo', 25),
    R('anello_stelle', {'ambra_stelle': 4, 'lingotto_nimbite': 1}, 'maglio'),
    R('dardo_stella', {'scheggia_stella': 1, 'legno': 2}, 'ceppo', 25),
    R('polvere_luminosa', {'polvere_falena': 2}, 'alambicco', 2),
    R('anello_orbita_forgiato', {'anello_orbita': 3, 'lingotto_nimbite': 2}, 'maglio'),
    R('collana_denti_stelle', {'dente_stelle': 8, 'seta_cielo': 2}, 'telaio'),
]
