"""Le righe del bestiario del sottosuolo e dei liquidi (voce 133): le usa tools/gen_bestiario.py."""


def P(*cols):
    return list(cols)


def R(out, ins, st, q=1):
    return {'out': out, 'qty': q, 'in': ins, 'station': st}


UNDER = [
    # Sottobosco di radici
    dict(id='radicello_ladro', name='Radicello ladro', tier=2, half=[6, 6], speed=90, beh=['cammina', 'ladro'], strata=[1], weight=4,
         p={'sight': 18, 'steal': 4}, hp=0.7, dmg=0.6,
         body={'plan': 'quadrupede', 'w': 16, 'h': 14, 'pal': P('#2a1c16', '#443024', '#664834', '#8e6a4c', '#c8a078'), 'eye': '#90ff70', 'tail': True},
         aff={'weak': ['brace'], 'resist': ['spora']}, fam=('radicelli', 'Radicelli', False, 'neutro'),
         mat=('radichetta', 'Radichetta rubata', ['seme', 'radice'], 'Un radicello ne porta sempre una in bocca.'),
         trophy=('bottino_radicello', 'Bottino del radicello', ['sacca', 'radice'])),
    dict(id='lombrico_radice', name='Lombrico di radice', tier=2, half=[9, 5], speed=55, beh=['cammina', 'sbuca'], strata=[1, 2], weight=4,
         p={'sight': 14, 'windup': 1.1, 'out_time': 4.0}, hp=1.3,
         body={'plan': 'serpe', 'w': 22, 'h': 10, 'pal': P('#3a1c24', '#5a2e38', '#80465a', '#b06a80', '#e0a0b0'), 'eye': '#ffe070', 'marks': 'strisce', 'mark': '#e0a0b0'},
         aff={'weak': ['gelo'], 'resist': ['spora']}, fam=('lombrichi', 'Lombrichi di radice', False, 'scavatore'),
         mat=('muco_lombrico', 'Muco di lombrico', ['gel', 'radice'], 'Tiene insieme la terra (e le dita).'),
         trophy=('anello_lombrico', 'Anello di lombrico', ['anello', 'radice'])),
    # Caverne d'ardesia
    dict(id='pipistrello_eco', name="Pipistrello dell'eco", tier=2, half=[6, 5], speed=100, fly=True, beh=['vola', 'fotofobo'], strata=[2], weight=5,
         p={'sight': 24, 'hover': 20.0, 'wobble': 50.0, 'dark_mult': 1.4}, hp=0.6, group=[2, 4],
         body={'plan': 'uccello', 'w': 16, 'h': 12, 'pal': P('#141420', '#262638', '#3e3e58', '#62628a', '#a0a0c8'), 'eye': '#ff5050', 'wings': '#262638'},
         aff={'weak': ['luce'], 'resist': ['vuoto']}, fam=('pipistrelli_ardesia', "Pipistrelli dell'eco", False, 'volante'),
         mat=('membrana_eco', "Membrana dell'eco", ['membrana', 'ardesia'], 'Vibra a ogni suono.'),
         trophy=('orecchio_eco', "Orecchio dell'eco", ['essenza', 'ardesia'])),
    dict(id='carapace_ardesia', name="Carapace d'ardesia", tier=2, half=[9, 7], speed=40, beh=['cammina', 'carica', 'scudo'], strata=[2, 3], weight=4,
         p={'sight': 16, 'charge': 190.0, 'charge_range': 6, 'charge_time': 0.6, 'charge_cool': 4.0, 'turn': 1.0}, hp=1.4, **{'def': 3},
         body={'plan': 'insetto', 'w': 22, 'h': 16, 'pal': P('#1e2636', '#30405a', '#4c5e80', '#7a90b4', '#b8c8e0'), 'eye': '#ffb050', 'marks': 'punte', 'mark': '#7a90b4'},
         aff={'weak': ['linfa'], 'resist': ['gelo']}, fam=('carapaci', "Carapaci d'ardesia", False, 'predatore', {'prey': ['radicelli']}),
         mat=('lastra_carapace', 'Lastra di carapace', ['scaglia', 'ardesia'], "Si scheggia a strati, come l'ardesia."),
         trophy=('scudo_carapace', 'Scudo di carapace intero', ['scaglia', 'ardesia'])),
    # Profondità della Linfa
    dict(id='lucciola_guaritrice', name='Lucciola guaritrice', tier=3, half=[6, 6], speed=80, fly=True, beh=['vola', 'guaritore'], strata=[3], weight=4,
         p={'sight': 20, 'hover': 40.0, 'wobble': 40.0, 'heal_every': 4.5, 'heal': 0.2, 'heal_r': 9}, hp=0.6, dmg=0.4, glow=True,
         body={'plan': 'insetto', 'w': 16, 'h': 14, 'pal': P('#0c2a2a', '#145050', '#1e8080', '#50c0b0', '#c0fff0'), 'eye': '#ffffff', 'wings': '#50c0b0', 'marks': 'macchie', 'mark': '#c0fff0', 'glow': True},
         aff={'weak': ['vuoto'], 'resist': ['linfa']}, fam=('lucciole_guaritrici', 'Lucciole guaritrici', True, 'volante'),
         mat=('luce_guaritrice', 'Luce che cura', ['essenza', 'linfa'], 'Chiusa in un vasetto, fa ricrescere le foglie.'),
         trophy=('lanterna_viva', 'Lanterna viva', ['lanterna', 'linfa'])),
    dict(id='goccia_divisa', name='Goccia di Linfa che si divide', tier=3, half=[7, 7], speed=55, beh=['salta_verso', 'divide'], strata=[3], weight=5,
         p={'jump': 220.0, 'sight': 18, 'big_hit': 0.5, 'split_hp': 0.45}, glow=True,
         body={'plan': 'fluttuante', 'w': 16, 'h': 16, 'pal': P('#0a2a2a', '#10504e', '#1a8480', '#40c0b4', '#b0fff0'), 'eye': '#ffffff', 'glow': True},
         aff={'weak': ['brace'], 'resist': ['linfa']}, fam=('gocce', 'Gocce di Linfa', True, 'neutro'),
         mat=('nucleo_goccia', 'Nucleo di goccia', ['gemma', 'linfa'], 'Senza di lui, la goccia torna Linfa.'),
         trophy=('goccia_madre', 'Goccia madre', ['goccia', 'linfa'])),
    dict(id='brucatore_profondo', name='Brucatore dei funghi profondi', tier=3, half=[10, 7], speed=45, beh=['cammina', 'fugge'], strata=[3], weight=4,
         p={'sight': 12, 'flee': 12}, docile=True, hp=1.3, dmg=0.5,
         body={'plan': 'quadrupede', 'w': 24, 'h': 18, 'pal': P('#1a2a24', '#2c4638', '#446850', '#6a9a72', '#b0e0a8'), 'eye': '#fff0a0', 'marks': 'macchie', 'mark': '#80f0c0', 'glow': True, 'horns': 1},
         aff={'weak': ['brace'], 'resist': ['spora']}, fam=('brucatori', 'Brucatori profondi', False, 'erbivoro', {'nest': {'type': 'erba', 'n': 4}}),
         mat=('lana_fungo', 'Lana di fungo', ['seta', 'fungo'], 'Morbida e un poco luminosa.'),
         trophy=('corno_brucatore', 'Corno di brucatore', ['artiglio', 'fungo'])),
    # Il Fondo
    dict(id='talpa_vuoto', name='Talpa del Vuoto', tier=3, half=[8, 6], speed=65, beh=['cammina', 'sbuca'], strata=[4], weight=4,
         p={'sight': 16, 'windup': 0.9, 'out_time': 4.0},
         body={'plan': 'quadrupede', 'w': 20, 'h': 14, 'pal': P('#140e20', '#241838', '#382858', '#5a4488', '#9a80d0'), 'eye': '#e070ff', 'marks': 'punte', 'mark': '#9a80d0', 'glow': True},
         aff={'weak': ['luce'], 'resist': ['vuoto']}, fam=('talpe_vuoto', 'Talpe del Vuoto', True, 'scavatore'),
         mat=('artiglio_vuoto', 'Artiglio del Vuoto', ['artiglio', 'vuotite'], "Scava dove non c'è niente."),
         trophy=('muso_vuoto', 'Muso del Vuoto', ['essenza', 'vuotite'])),
    dict(id='pascolante_vuoto', name='Pascolante del Vuoto', tier=3, half=[10, 8], speed=40, beh=['cammina', 'fugge'], strata=[4], weight=4,
         p={'sight': 12, 'flee': 12}, docile=True, hp=1.4, dmg=0.5,
         body={'plan': 'lumaca', 'w': 24, 'h': 18, 'pal': P('#140e20', '#241838', '#382858', '#6a54a0', '#c0b0f0'), 'eye': '#ffffff', 'marks': 'macchie', 'mark': '#e0a0ff', 'glow': True},
         aff={'weak': ['luce'], 'resist': ['vuoto']}, fam=('pascolanti', 'Pascolanti del Vuoto', False, 'erbivoro', {'nest': {'type': 'erba', 'n': 4}}),
         mat=('vello_vuoto', 'Vello del Vuoto', ['seta', 'vuotite'], 'Nero, e dentro ci sono le stelle.'),
         trophy=('conchiglia_vuoto', 'Conchiglia del Vuoto', ['scaglia', 'vuotite'])),
    dict(id='bolla_vuoto', name='Bolla del Vuoto', tier=3, half=[7, 7], speed=50, fly=True, beh=['vola', 'scoppia'], strata=[4], weight=4,
         p={'sight': 20, 'hover': 0.0, 'wobble': 20.0, 'fuse': 1.1, 'fuse_r': 2.4, 'blast_r': 2.6}, hp=0.7,
         body={'plan': 'fluttuante', 'w': 16, 'h': 16, 'pal': P('#0a0614', '#1a1030', '#2e1e54', '#5a40a0', '#c0a0ff'), 'eye': '#ff80ff', 'glow': True},
         aff={'weak': ['luce'], 'resist': ['vuoto']}, fam=('bolle', 'Bolle del Vuoto', True, 'neutro'),
         mat=('pellicola_vuoto', 'Pellicola del Vuoto', ['membrana', 'vuotite'], "Quello che resta di una bolla: trattiene l'aria."),
         trophy=('bolla_intera', 'Bolla intera', ['gemma', 'vuotite'])),
    # Caverne del cristallo cantante
    dict(id='corista_cristallo', name='Corista di cristallo', tier=3, half=[7, 8], speed=50, beh=['cammina', 'richiamo'], strata=[2], weight=0, under='canto', uw=6,
         p={'sight': 18, 'call_time': 1.6, 'call_n': 2, 'calls': 2}, glow=True,
         body={'plan': 'anfibio', 'w': 18, 'h': 16, 'pal': P('#1a2440', '#2c3e66', '#4a64a0', '#80a8e0', '#e0f0ff'), 'eye': '#fff0a0', 'marks': 'punte', 'mark': '#e0f0ff', 'glow': True},
         aff={'weak': ['vuoto'], 'resist': ['luce']}, fam=('coristi', 'Coristi di cristallo', False, 'neutro'),
         mat=('corda_cristallo', 'Corda di cristallo', ['seta', 'cristallo'], 'Pizzicata, canta.'),
         trophy=('gola_corista', 'Gola del corista', ['essenza', 'cristallo'])),
    dict(id='mimo_cantante', name='Grappolo che morde', tier=3, half=[7, 7], speed=80, beh=['salta_verso', 'mimetico'], strata=[2], weight=0, under='canto', uw=4,
         p={'jump': 240.0, 'sight': 18, 'look': 'cristallo_linfa', 'wake': 3.0}, dmg=1.2,
         body={'plan': 'fluttuante', 'w': 16, 'h': 16, 'pal': P('#10283a', '#1a4a66', '#2c78a0', '#60b8e0', '#d0f4ff'), 'eye': '#ff5070', 'marks': 'punte', 'mark': '#d0f4ff', 'glow': True},
         aff={'weak': ['spora'], 'resist': ['luce']}, fam=('grappoli', 'Grappoli che mordono', False, 'predatore', {'prey': ['brucacristalli']}),
         mat=('dente_cristallo', 'Dente di cristallo', ['artiglio', 'cristallo'], 'Sembrava una gemma. Morde come un dente.'),
         trophy=('cuore_grappolo', 'Cuore del grappolo', ['gemma', 'cristallo'])),
    dict(id='brucacristalli', name='Brucacristalli', tier=3, half=[8, 6], speed=40, beh=['cammina', 'fugge'], strata=[2], weight=0, under='canto', uw=5,
         p={'sight': 12, 'flee': 10}, docile=True, hp=1.1, dmg=0.4,
         body={'plan': 'lumaca', 'w': 20, 'h': 14, 'pal': P('#1a2440', '#2c3e66', '#4a64a0', '#80c0f0', '#f0ffff'), 'eye': '#101820', 'marks': 'punte', 'mark': '#c0f0ff', 'glow': True},
         aff={'weak': ['brace'], 'resist': ['luce']}, fam=('brucacristalli', 'Brucacristalli', False, 'erbivoro', {'nest': {'type': 'tana', 'n': 4}}),
         mat=('sabbia_cantante', 'Sabbia cantante', ['polvere', 'cristallo'], 'Cristallo masticato: fischia ancora.'),
         trophy=('guscio_cantante', 'Guscio cantante', ['scaglia', 'cristallo'])),
    # Giungle di radici
    dict(id='scimmia_liana', name='Scimmia di liana', tier=2, half=[7, 8], speed=110, beh=['cammina', 'ladro'], strata=[1], weight=0, under='giungla', uw=5,
         p={'sight': 22, 'steal': 5}, hp=0.8, dmg=0.6,
         body={'plan': 'quadrupede', 'w': 18, 'h': 18, 'pal': P('#1e2a14', '#344a22', '#4e6e34', '#78a050', '#c0e090'), 'eye': '#ffd040', 'tail': True},
         aff={'weak': ['brace'], 'resist': ['spora']}, fam=('scimmie_liana', 'Scimmie di liana', True, 'neutro'),
         mat=('pelo_liana', 'Pelo di scimmia', ['seta', 'muschio'], 'Intrecciato alla liana, regge qualunque cosa.'),
         trophy=('coda_prensile', 'Coda prensile', ['penna', 'muschio'])),
    dict(id='ragno_giungla', name='Ragno della giungla', tier=2, half=[8, 6], speed=65, beh=['cammina', 'tessitore'], strata=[1], weight=0, under='giungla', uw=5,
         p={'sight': 18, 'web_every': 5.0}, hp=1.1,
         body={'plan': 'insetto', 'w': 20, 'h': 14, 'pal': P('#1a1a0e', '#2e2e18', '#4a4a26', '#78783e', '#c0c070'), 'eye': '#ff4040', 'marks': 'strisce', 'mark': '#c0c070'},
         aff={'weak': ['brace'], 'resist': ['spora']}, fam=('ragni_giungla', 'Ragni della giungla', False, 'predatore', {'prey': ['bufali_radice']}),
         mat=('seta_giungla', 'Seta della giungla', ['seta', 'radice'], 'Più forte della seta di radice.'),
         trophy=('filiera_giungla', 'Filiera del ragno', ['essenza', 'radice'])),
    dict(id='bufalo_radice', name='Bufalo di radice', tier=2, half=[12, 9], speed=60, beh=['cammina', 'fugge', 'pastore'], strata=[1], weight=0, under='giungla', uw=4,
         p={'sight': 14, 'flee': 12, 'herd_r': 12}, docile=True, hp=2.0, dmg=0.8, group=[2, 3],
         body={'plan': 'quadrupede', 'w': 28, 'h': 22, 'pal': P('#2a1e14', '#443222', '#644a34', '#8e6c4c', '#c8a078'), 'eye': '#101010', 'horns': 2},
         aff={'weak': ['spora'], 'resist': ['gelo']}, fam=('bufali_radice', 'Bufali di radice', False, 'erbivoro', {'nest': {'type': 'erba', 'n': 4}}),
         mat=('cuoio_radice', 'Cuoio di bufalo', ['seta', 'radice'], 'Duro come la corteccia.'),
         trophy=('corna_bufalo', 'Corna di bufalo', ['artiglio', 'radice'])),
    # Laghi sotterranei: la lontra ruba il pesce dalla lenza
    dict(id='lontra_lago', name='Lontra di lago', tier=3, half=[9, 5], speed=100, beh=['cammina', 'ladro'], strata=[2], weight=0, under='lago', uw=5,
         p={'sight': 20, 'steal': 3, 'steal_fish': True}, hp=0.9, dmg=0.6,
         body={'plan': 'quadrupede', 'w': 22, 'h': 12, 'pal': P('#1e1a16', '#342c24', '#524434', '#7a6450', '#b89c80'), 'eye': '#101010', 'tail': True},
         aff={'weak': ['brace'], 'resist': ['gelo']}, fam=('lontre', 'Lontre di lago', True, 'predatore', {'prey': ['granchi']}),
         mat=('pelo_lontra', 'Pelo di lontra', ['seta', 'humus'], 'Non si bagna mai.'),
         trophy=('pesce_lontra', 'Il pesce della lontra', ['essenza', 'lagunite'])),
    # Catacombe dei Seminatori
    dict(id='ossuto_scudato', name='Ossuto scudato', tier=3, half=[8, 10], speed=50, beh=['cammina', 'carica', 'scudo'], strata=[2, 3], weight=0, under='catacombe', uw=5,
         p={'sight': 18, 'charge': 200.0, 'charge_range': 6, 'charge_time': 0.6, 'charge_cool': 4.0, 'turn': 0.9}, hp=1.2, **{'def': 2},
         body={'plan': 'anfibio', 'w': 18, 'h': 22, 'pal': P('#2a2822', '#46423a', '#6a6458', '#9a9282', '#e0d8c4'), 'eye': '#6ff0d8', 'marks': 'strisce', 'mark': '#e0d8c4', 'glow': True},
         aff={'weak': ['luce'], 'resist': ['vuoto']}, fam=('ossuti', 'Ossuti', False, 'predatore', {'prey': ['ratti']}),
         mat=('osso_seminatore', 'Osso levigato', ['artiglio', 'sem'], 'Liscio come una pietra dei Seminatori.'),
         trophy=('teschio_rune', 'Teschio con le rune', ['essenza', 'sem'])),
    dict(id='spirito_catacomba', name='Spirito delle catacombe', tier=3, half=[7, 9], speed=75, fly=True, beh=['vola', 'fotofobo'], strata=[2, 3], weight=0, under='catacombe', uw=5,
         p={'sight': 22, 'hover': 20.0, 'wobble': 30.0, 'dark_mult': 1.7}, glow=True,
         body={'plan': 'fluttuante', 'w': 16, 'h': 20, 'pal': P('#101a1a', '#1c3030', '#2c4c4a', '#4a8078', '#a0f0e0'), 'eye': '#a0f0e0', 'marks': 'strisce', 'mark': '#a0f0e0', 'glow': True},
         aff={'weak': ['luce'], 'resist': ['vuoto']}, fam=('spiriti_catacombe', 'Spiriti delle catacombe', False, 'volante'),
         mat=('ectoplasma', 'Velo di spirito', ['velo', 'sem'], 'Freddo, leggero, e sussurra nomi.'),
         trophy=('lanterna_spirito', 'Lanterna dello spirito', ['lanterna', 'sem'])),
    dict(id='ratto_catacomba', name='Ratto delle catacombe', tier=2, half=[6, 4], speed=100, beh=['cammina', 'rosicchia'], strata=[2, 3], weight=0, under='catacombe', uw=6,
         p={'sight': 18, 'gnaw_every': 1.5}, hp=0.6, dmg=0.7, group=[2, 4],
         body={'plan': 'quadrupede', 'w': 16, 'h': 10, 'pal': P('#1a1a1a', '#2e2e2c', '#4a4844', '#76706a', '#b0a8a0'), 'eye': '#ff3030', 'tail': True},
         aff={'weak': ['brace'], 'resist': ['vuoto']}, fam=('ratti', 'Ratti delle catacombe', False, 'neutro'),
         mat=('dente_ratto', 'Dente di ratto', ['artiglio', 'ardesia'], 'Rosicchia anche il legno delle porte.'),
         trophy=('re_ratti', 'Nodo del re dei ratti', ['essenza', 'ardesia'])),
    # I liquidi: nascono nel loro liquido
    dict(id='luccio_stagno', name='Luccio degli stagni', tier=2, half=[10, 4], speed=90, fly=True, beh=['nuota', 'tuffatore'], strata=[], weight=4, water=True, liquid='acqua',
         p={'sight': 16, 'bite': True, 'leap_range': 8, 'leap_cool': 5.0, 'steal_fish': True},
         body={'plan': 'serpe', 'w': 22, 'h': 10, 'pal': P('#1a2a1a', '#2c442c', '#466a44', '#709a68', '#c0e0a8'), 'eye': '#ffd040', 'marks': 'strisce', 'mark': '#c0e0a8'},
         aff={'weak': ['brace'], 'resist': ['gelo']}, fam=('lucci', 'Lucci degli stagni', False, 'predatore'),
         mat=('dente_luccio', 'Dente di luccio', ['artiglio', 'lagunite'], 'Ne ha tre file: ne perde sempre qualcuno.'),
         trophy=('mascella_luccio', 'Mascella di luccio', ['artiglio', 'lagunite'])),
    dict(id='salamandra_linfa', name='Salamandra di Linfa', tier=3, half=[9, 4], speed=80, fly=True, beh=['nuota', 'tuffatore'], strata=[], weight=3, water=True, liquid='linfa',
         p={'sight': 16, 'bite': True, 'leap_range': 9, 'leap_cool': 4.5}, glow=True,
         body={'plan': 'serpe', 'w': 22, 'h': 10, 'pal': P('#0a2a2a', '#10504e', '#1a8480', '#40c0b4', '#b0fff0'), 'eye': '#ffffff', 'marks': 'macchie', 'mark': '#ffffff', 'glow': True, 'tail': True},
         aff={'weak': ['brace'], 'resist': ['linfa']}, fam=('salamandre_linfa', 'Salamandre di Linfa', True, 'predatore'),
         mat=('pelle_linfa', 'Pelle di salamandra di Linfa', ['membrana', 'linfa'], 'Bagnata di Linfa per sempre.'),
         trophy=('cresta_linfa', 'Cresta di Linfa', ['penna', 'linfa'])),
    dict(id='anguilla_brace', name='Anguilla di brace', tier=3, half=[12, 4], speed=85, fly=True, beh=['nuota', 'tuffatore'], strata=[], weight=3, water=True, liquid='brace',
         p={'sight': 16, 'bite': True, 'leap_range': 9, 'leap_cool': 4.0}, glow=True, hp=1.2,
         body={'plan': 'serpe', 'w': 26, 'h': 10, 'pal': P('#3a1008', '#6a1c0c', '#a83414', '#e06a24', '#ffd070'), 'eye': '#fff0a0', 'marks': 'strisce', 'mark': '#ffd070', 'glow': True},
         aff={'weak': ['gelo'], 'resist': ['brace']}, fam=('anguille_brace', 'Anguille di brace', True, 'predatore'),
         mat=('pinna_brace', 'Pinna di brace', ['membrana', 'brace'], 'Nuota nella brace, e la brace le obbedisce.'),
         trophy=('cuore_anguilla', "Cuore d'anguilla", ['essenza', 'tizzonite'])),
    # voce 133: altre tre per i laghi e i liquidi (i buchi misurati da tools/ecosistemi.gd)
    dict(id='tartaruga_lago', name='Tartaruga di lago', tier=3, half=[10, 6], speed=30, beh=['cammina', 'guscio'], strata=[2], weight=0, under='lago', uw=4,
         p={'sight': 10, 'shell_time': 3.0}, docile=True, hp=1.6, dmg=0.5, **{'def': 4},
         body={'plan': 'lumaca', 'w': 24, 'h': 14, 'pal': P('#1a2418', '#2c3c28', '#465e3e', '#6c8a5c', '#a8c890'), 'eye': '#101010', 'marks': 'macchie', 'mark': '#a8c890'},
         aff={'weak': ['brace'], 'resist': ['gelo']}, fam=('tartarughe', 'Tartarughe di lago', True, 'erbivoro', {'nest': {'type': 'tana', 'n': 3}}),
         mat=('guscio_tartaruga', 'Guscio di tartaruga', ['scaglia', 'muschio'], 'Duro e liscio: un piatto, uno scudo, un tetto.'),
         trophy=('tartaruga_antica', 'Guscio antico', ['scaglia', 'muschio'])),
    dict(id='carpa_brucatrice', name='Carpa brucatrice', tier=2, half=[9, 5], speed=55, fly=True, beh=['nuota', 'fugge'], strata=[], weight=5, water=True, liquid='acqua',
         p={'sight': 10, 'flee': 8}, docile=True, dmg=0.3,
         body={'plan': 'serpe', 'w': 20, 'h': 10, 'pal': P('#3a2a10', '#6a4a1a', '#a0702a', '#d8a040', '#fff0a0'), 'eye': '#101010', 'marks': 'macchie', 'mark': '#fff0a0'},
         aff={'weak': ['brace'], 'resist': ['spora']}, fam=('carpe', 'Carpe brucatrici', True, 'erbivoro'),
         mat=('squama_carpa', 'Squama di carpa', ['scaglia', 'ambra'], 'Dorata: dicono che porti fortuna.'),
         trophy=('carpa_dorata', 'Carpa dorata', ['essenza', 'ambra'])),
    dict(id='polpo_stagno', name='Polpo degli stagni', tier=2, half=[8, 7], speed=60, fly=True, beh=['nuota', 'ladro'], strata=[], weight=3, water=True, liquid='acqua',
         p={'sight': 12, 'bite': True, 'steal': 3}, hp=0.9, dmg=0.6,
         body={'plan': 'fluttuante', 'w': 18, 'h': 16, 'pal': P('#2a1030', '#4a1e54', '#743484', '#a860b8', '#e8b0f0'), 'eye': '#fff0a0', 'marks': 'macchie', 'mark': '#e8b0f0'},
         aff={'weak': ['brace'], 'resist': ['gelo']}, fam=('polpi', 'Polpi degli stagni', False, 'neutro'),
         mat=('inchiostro_polpo', 'Inchiostro di polpo', ['goccia', 'nottilite'], 'Nero come la notte: scrive da solo.'),
         trophy=('tentacolo_polpo', 'Tentacolo che stringe', ['penna', 'nottilite'])),
]

UNDER_ITEMS = {
    'borsa_radicello': {'name': 'Tasca del radicello', 'kind': 'accessorio', 'icon': ['sacca', 'radice'], 'acc': {'luck': 0.06, 'dig': 1.05}, 'desc': 'Fortuna +6%; scavo +5%.'},
    'unguento_lombrico': {'name': 'Unguento di lombrico', 'kind': 'consumabile', 'icon': ['pozione', 'radice'], 'boon': ['scorza', 180.0], 'stack': 20, 'desc': 'Per 3 minuti la pelle diventa scorza.'},
    'orecchie_eco': {'name': "Cuffie dell'eco", 'kind': 'accessorio', 'icon': ['membrana', 'ardesia'], 'acc': {'halo': 1.2, 'stealth': 0.9}, 'desc': 'Alone +20%; le creature ti notano più tardi.'},
    'scudo_ardesia_vivo': {'name': 'Scudo di carapace', 'kind': 'accessorio', 'icon': ['scudo', 'ardesia'], 'acc': {'defense': 4}, 'desc': '+4 Scorza.'},
    'vasetto_guaritore': {'name': 'Vasetto della luce che cura', 'kind': 'consumabile', 'icon': ['pozione', 'linfa'], 'heal': 80, 'stack': 20, 'desc': 'Cura 80 Vita.'},
    'anello_goccia': {'name': 'Anello di goccia', 'kind': 'accessorio', 'icon': ['anello', 'linfa'], 'acc': {'linfa_regen': 1.2, 'magic': 1.05}, 'desc': 'La Linfa ricresce +20%; incantesimi +5%.'},
    'mantello_lana_fungo': {'name': 'Mantello di lana di fungo', 'kind': 'accessorio', 'icon': ['velo', 'fungo'], 'acc': {'regen': 1.1, 'caldo': 0.3}, 'desc': 'La Vita ricresce +10%; freddo: protegge un poco.'},
    'guanti_vuoto': {'name': 'Guanti del Vuoto', 'kind': 'accessorio', 'icon': ['guanto', 'vuotite'], 'acc': {'dig': 1.18}, 'desc': 'Scavo +18%.'},
    'mantello_vello_vuoto': {'name': 'Mantello di vello del Vuoto', 'kind': 'accessorio', 'icon': ['velo', 'vuotite'], 'acc': {'stealth': 0.85, 'defense': 2}, 'desc': 'Le creature ti notano più tardi; +2 Scorza.'},
    'bolla_respiro': {'name': 'Bolla da respiro', 'kind': 'accessorio', 'icon': ['gemma', 'vuotite'], 'acc': {'respiro': 1.8}, 'desc': "Sott'acqua il respiro dura +80%."},
    'arpa_cristallo': {'name': 'Arpa di cristallo', 'kind': 'accessorio', 'icon': ['amuleto', 'cristallo'], 'acc': {'magic': 1.1}, 'desc': 'Incantesimi +10%.'},
    'lama_dente_cristallo': {'name': 'Lama di dente di cristallo', 'kind': 'spada', 'icon': ['lama', 'cristallo'], 'tier': 4, 'damage': 24, 'speed': 2.8, 'knockback': 1.6, 'desc': 'Una lama che canta quando colpisce.'},
    'polvere_cantante': {'name': 'Polvere cantante', 'kind': 'consumabile', 'icon': ['pozione', 'cristallo'], 'boon': ['bagliore', 300.0], 'stack': 20, 'desc': 'Per 5 minuti fai più luce attorno a te.'},
    'fune_liana': {'name': 'Fune di pelo di liana', 'kind': 'accessorio', 'icon': ['seta', 'muschio'], 'acc': {'wall': True}, 'desc': 'Ci si aggrappa alle pareti e si salta di lì.'},
    'arco_giungla': {'name': 'Arco di seta della giungla', 'kind': 'arco', 'icon': ['arco', 'radice'], 'tier': 3, 'damage': 16, 'speed': 2.2, 'knockback': 1.0, 'desc': 'Una corda che non si spezza mai.'},
    'corazza_cuoio': {'name': 'Corpetto di cuoio di bufalo', 'kind': 'accessorio', 'icon': ['scudo', 'radice'], 'acc': {'defense': 3, 'fall_safe': True}, 'desc': '+3 Scorza; le cadute non fanno male.'},
    'guanti_lontra': {'name': 'Guanti di pelo di lontra', 'kind': 'accessorio', 'icon': ['guanto', 'humus'], 'acc': {'fish_luck': 0.1, 'respiro': 1.3}, 'desc': 'Fortuna di pesca +10%; respiro +30%.'},
    'amuleto_ossa': {'name': "Amuleto d'osso levigato", 'kind': 'accessorio', 'icon': ['amuleto', 'sem'], 'acc': {'defense': 2, 'thorns': 6}, 'desc': '+2 Scorza; chi ti tocca si ferisce (6).'},
    'lanterna_velo': {'name': 'Lanterna del velo di spirito', 'kind': 'accessorio', 'icon': ['lanterna', 'sem'], 'acc': {'halo': 1.4, 'magic': 1.04}, 'desc': 'Alone +40%; incantesimi +4%.'},
    'trappola_denti': {'name': 'Collana di denti di ratto', 'kind': 'accessorio', 'icon': ['amuleto', 'ardesia'], 'acc': {'damage': 1.05, 'atk_speed': 1.05}, 'desc': 'Danno +5%, colpi +5%.'},
    'mantello_linfa': {'name': 'Mantello di pelle di Linfa', 'kind': 'accessorio', 'icon': ['velo', 'linfa'], 'acc': {'respiro': 1.5, 'linfa_regen': 1.1}, 'desc': 'Respiro +50%; la Linfa ricresce +10%.'},
    'pinne_brace': {'name': 'Pinne di brace', 'kind': 'accessorio', 'icon': ['membrana', 'brace'], 'acc': {'fresco': 0.6, 'run': 1.04}, 'desc': 'Calore: protegge al 60%; corsa +4%.'},
    'scudo_tartaruga': {'name': 'Scudo di guscio di tartaruga', 'kind': 'accessorio', 'icon': ['scudo', 'muschio'], 'acc': {'defense': 5, 'respiro': 1.2}, 'desc': '+5 Scorza; respiro +20%.'},
    'amuleto_carpa': {'name': 'Amuleto di squama dorata', 'kind': 'accessorio', 'icon': ['amuleto', 'ambra'], 'acc': {'luck': 0.07, 'fish_luck': 0.05}, 'desc': 'Fortuna +7%; fortuna di pesca +5%.'},
    'tintura_inchiostro': {'name': "Boccetta d'inchiostro", 'kind': 'consumabile', 'icon': ['pozione', 'nottilite'], 'boon': ['fortuna', 240.0], 'stack': 20, 'desc': "Scrivere il tuo nome con l'inchiostro del polpo porta fortuna: per 4 minuti."},
    'collana_luccio': {'name': 'Collana di denti di luccio', 'kind': 'accessorio', 'icon': ['amuleto', 'lagunite'], 'acc': {'fish_luck': 0.08, 'fish_size': 0.1}, 'desc': 'Fortuna di pesca +8%; pesci più grandi.'},
    'talismano_sottobosco': {'name': 'Talismano del sottobosco', 'kind': 'accessorio', 'icon': ['amuleto', 'radice'], 'acc': {'luck': 0.08, 'dig': 1.08}, 'desc': 'Fortuna +8%; scavo +8%.'},
    'talismano_caverne': {'name': 'Talismano delle caverne', 'kind': 'accessorio', 'icon': ['amuleto', 'ardesia'], 'acc': {'defense': 3, 'halo': 1.2}, 'desc': '+3 Scorza; alone +20%.'},
    'talismano_profondo': {'name': 'Talismano del profondo', 'kind': 'accessorio', 'icon': ['amuleto', 'linfa'], 'acc': {'regen': 1.15, 'linfa_regen': 1.15}, 'desc': 'Vita e Linfa ricrescono +15%.'},
    'talismano_fondo': {'name': 'Talismano del Fondo', 'kind': 'accessorio', 'icon': ['amuleto', 'vuotite'], 'acc': {'damage': 1.08, 'stealth': 0.9}, 'desc': 'Danno +8%; le creature ti notano più tardi.'},
    'talismano_canto': {'name': 'Talismano del cristallo cantante', 'kind': 'accessorio', 'icon': ['amuleto', 'cristallo'], 'acc': {'magic': 1.12, 'luck': 0.05}, 'desc': 'Incantesimi +12%; fortuna +5%.'},
    'talismano_giungla': {'name': 'Talismano della giungla', 'kind': 'accessorio', 'icon': ['amuleto', 'muschio'], 'acc': {'run': 1.06, 'jump': 1.06}, 'desc': 'Corsa e salto +6%.'},
    'talismano_acque': {'name': 'Talismano delle acque profonde', 'kind': 'accessorio', 'icon': ['amuleto', 'lagunite'], 'acc': {'fish_luck': 0.15, 'respiro': 1.5}, 'desc': 'Fortuna di pesca +15%; respiro +50%.'},
    'talismano_catacombe': {'name': 'Talismano delle catacombe', 'kind': 'accessorio', 'icon': ['amuleto', 'sem'], 'acc': {'defense': 3, 'magic': 1.06}, 'desc': '+3 Scorza; incantesimi +6%.'},
}

UNDER_RECIPES = [
    R('borsa_radicello', {'radichetta': 8, 'seta_radice': 3}, 'telaio'),
    R('unguento_lombrico', {'muco_lombrico': 2, 'gelatina': 1}, 'alambicco', 2),
    R('orecchie_eco', {'membrana_eco': 10, 'seta_radice': 3}, 'telaio'),
    R('scudo_ardesia_vivo', {'lastra_carapace': 10, 'lingotto_legnoferro': 4}, 'maglio'),
    R('vasetto_guaritore', {'luce_guaritrice': 2, 'gelatina': 1}, 'alambicco', 2),
    R('anello_goccia', {'nucleo_goccia': 6, 'lingotto_ambra': 2}, 'maglio'),
    R('mantello_lana_fungo', {'lana_fungo': 10, 'seta_radice': 3}, 'telaio'),
    R('guanti_vuoto', {'artiglio_vuoto': 8, 'lingotto_vuoto': 2}, 'maglio'),
    R('mantello_vello_vuoto', {'vello_vuoto': 10, 'seta_radice': 4}, 'telaio'),
    R('bolla_respiro', {'pellicola_vuoto': 8, 'lingotto_ambra': 2}, 'maglio'),
    R('arpa_cristallo', {'corda_cristallo': 8, 'lingotto_ambra': 2}, 'maglio'),
    R('lama_dente_cristallo', {'dente_cristallo': 10, 'lingotto_legnoferro': 5}, 'maglio'),
    R('polvere_cantante', {'sabbia_cantante': 3, 'gelatina': 1}, 'alambicco', 2),
    R('fune_liana', {'pelo_liana': 10, 'corda_liana': 4}, 'telaio'),
    R('arco_giungla', {'seta_giungla': 10, 'legno': 8}, 'telaio'),
    R('corazza_cuoio', {'cuoio_radice': 10, 'seta_radice': 3}, 'telaio'),
    R('guanti_lontra', {'pelo_lontra': 8, 'seta_radice': 2}, 'telaio'),
    R('amuleto_ossa', {'osso_seminatore': 8, 'lingotto_ambra': 2}, 'maglio'),
    R('lanterna_velo', {'ectoplasma': 8, 'lingotto_radicite': 3}, 'maglio'),
    R('trappola_denti', {'dente_ratto': 10, 'seta_radice': 2}, 'telaio'),
    R('mantello_linfa', {'pelle_linfa': 10, 'seta_radice': 4}, 'telaio'),
    R('pinne_brace', {'pinna_brace': 8, 'lingotto_tizzonite': 2}, 'maglio'),
    R('scudo_tartaruga', {'guscio_tartaruga': 6, 'lingotto_legnoferro': 3}, 'maglio'),
    R('amuleto_carpa', {'squama_carpa': 8, 'lingotto_ambra': 1}, 'maglio'),
    R('tintura_inchiostro', {'inchiostro_polpo': 2, 'gelatina': 1}, 'alambicco', 2),
    R('collana_luccio', {'dente_luccio': 8, 'seta_radice': 2}, 'telaio'),
    R('talismano_sottobosco', {'bottino_radicello': 1, 'anello_lombrico': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('talismano_caverne', {'orecchio_eco': 1, 'scudo_carapace': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('talismano_profondo', {'lanterna_viva': 1, 'goccia_madre': 1, 'corno_brucatore': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('talismano_fondo', {'muso_vuoto': 1, 'conchiglia_vuoto': 1, 'bolla_intera': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('talismano_canto', {'gola_corista': 1, 'cuore_grappolo': 1, 'guscio_cantante': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('talismano_giungla', {'coda_prensile': 1, 'filiera_giungla': 1, 'corna_bufalo': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('talismano_acque', {'pesce_lontra': 1, 'mascella_luccio': 1, 'cresta_linfa': 1, 'cuore_anguilla': 1, 'lingotto_ambra': 2}, 'maglio'),
    R('talismano_acque', {'tartaruga_antica': 1, 'carpa_dorata': 1, 'tentacolo_polpo': 1, 'lingotto_ambra': 3}, 'maglio'),
    R('talismano_catacombe', {'teschio_rune': 1, 'lanterna_spirito': 1, 're_ratti': 1, 'lingotto_ambra': 2}, 'maglio'),
]
